### ISSUE TITLE
"Error starting server. Please check the logs"

### ISSUE THREAD

**Issue by darrylgibbs** [assetto-corsa-web/accweb#103]
So I've just fired up the docker container, I've opened all appropriate ports etc, but I when I start the server, I get this error: **"Error starting server. Please check the logs"**

No logs are given though, at all.  So what now.  What info can I provide to assist?  Below is my **CONFIG.YML**

webserver:
  host: localhost:8080
  write_timeout: 5
  read_timeout: 5
  tls: false
  cert: path to ssl certificate
  private_key: path to ssl private key
auth:
  public_key_path: secrets/token.public
  private_key_path: secrets/token.private
  admin_password: weak
  moderator_password: weak
  read_only_password: weak
acc:
  server_path: "/home/darryl/accweb"
  server_exe: accServer.exe

config_path: config/
dev: true
loglevel: debug
cors:
  origins: "*"
  loglevel: info

**My DOCKER-COMPOSE.YML**

version: '3'

services:
  accweb:
    #image: accweb:latest
    image: kugel/accweb
    container_name : accweb-server
    restart: always
    ports:
      - 8080:8080
      - 9600:9600
    volumes:
      - "accweb:/accweb"
      - "acccerts:/sslcerts"
      - "accserver:/accserver"
    environment:
      ACCWEB_HOST: 0.0.0.0:8080
      ACCWEB_ENABLE_TLS: "false"
      ACCWEB_CERT_FILE: /sslcerts/certificate.crt
      ACCWEB_PRIV_FILE: /sslcerts/private.key
      ACCWEB_ADMIN_PASSWORD: weak
      ACCWEB_MOD_PASSWORD: weak
      ACCWEB_RO_PASSWORD: weak
      ACCWEB_LOGLEVEL: info 
      ACCWEB_CORS: "*"
    networks:
      - accnetwork

networks:
  accnetwork:
    
volumes:
  accweb:
  acccerts:
  accserver:

**Comment by Kugelschieber** [comment]
The docker image isn't really working at the moment. I need to create a better one. Originally I didn't plan to add docker support and it was contributed, so I'm a little bit lost when it comes to supporting it.

Can you go for the normal version until I've fixed it (probably with version 2.0)?

**Comment by darrylgibbs** [comment]
Sure thing... I'll give it a bash!

**Comment by Bmendess** [comment]
is adding double slashes apparently.... 

time="2020-10-17T17:52:03+01:00" level=error msg="Error reading source file" err="open F:\\Steam\\steamapps\\common\\Assetto Corsa Competizione\\server\\accServer.exe: The system cannot find the file specified." file="F:\\Steam\\steamapps\\common\\Assetto Corsa Competizione\\server\\accServer.exe"
time="2020-10-17T17:52:03+01:00" level=error msg="Error copying server files" error="open F:\\Steam\\steamapps\\common\\Assetto Corsa Competizione\\server\\accServer.exe: The system cannot find the file specified."

**Comment by Bmendess** [comment]
![image](https://user-images.githubusercontent.com/43620995/96348651-426b3280-10a2-11eb-9cbb-10640bd750c4.png)

**Comment by Kugelschieber** [comment]
Use forward slashes.

**Comment by Bmendess** [comment]
> Use forward slashes.

i'm using... everything was working fine before...

**Comment by Kugelschieber** [comment]
Well, it clearly states that it cannot find the server exe to copy. Check the paths and that it can access the directory.

**Comment by Bmendess** [comment]
> Well, it clearly states that it cannot find the server exe to copy. Check the paths and that it can access the directory.

![image](https://user-images.githubusercontent.com/43620995/96354501-52e5d200-10cf-11eb-84d2-92c9ebb23172.png)

**Comment by Kugelschieber** [comment]
Hmm, it looks like it cannot load your server configuration files. From what version did you upgrade? Did you run all the migration steps required (see changelog in the readme)?

**Comment by Dpaganini** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Marvin Blum<mailto:notifications@github.com>
Enviado:sábado, 17 de outubro de 2020 19:47
Para: assetto-corsa-web/accweb<mailto:accweb@noreply.github.com>
Cc:Subscribed<mailto:subscribed@noreply.github.com>
Assunto: Re: [assetto-corsa-web/accweb] "Error starting server. Please check the logs" (#103)


Hmm, it looks like it cannot load your server configuration files. From what version did you upgrade? Did you run all the migration steps required (see changelog in the readme)?

**Comment by Bmendess** [comment]
i didnt migrate or anything... it just stopped .... have no idea why... should i reinstall it again?

**Comment by Bmendess** [comment]
reinstalled everything, all good now!

**Comment by Kugelschieber** [comment]
I'm closing this for now.
