### ISSUE TITLE
Formation Lap Options

### ISSUE THREAD

**Issue by Menteroth** [assetto-corsa-web/accweb#104]
I couldn't find anything about this so just mentioning it. If you already have it in mind to add you can just close this issue. Just something I noticed in the server configuration wiki.
![image](https://user-images.githubusercontent.com/24851042/95655768-e46ea600-0b09-11eb-834f-5ba8d9568ccc.png)

I added the red dots myself to clearly point it out. So it's not something from the wiki warning about it not being supported or anything.

**Comment by Kugelschieber** [comment]
I'll look into the configuration again for v2.

**Comment by pedrofaria** [comment]
UI is according latest version. closing this issue
