### ISSUE TITLE
Log Output

### ISSUE THREAD

**Issue by Menteroth** [assetto-corsa-web/accweb#106]
Is that window supposed to do something? Rhetorical question I guess because I have never seen anything in any of those log windows on any server I checked I am running. It has always been completely empty. Even with active servers.

**Comment by Kugelschieber** [comment]
Not sure why it's not working for some people.

**Comment by Menteroth** [comment]
Hmm okay. Weird.

**Comment by Kugelschieber** [comment]
I'll look into it when adding it to v2.

**Comment by Menteroth** [comment]
So log output works on my Windows 10 64-bit PC. But the one it's not working on is Windows 8.1 64-bit. Hope that helps.

**Comment by Menteroth** [comment]
Where the server is hosted by the way. I tried both and log output only works when hosting on Windows 10 PC.

**Comment by Menteroth** [comment]
Seems to work on my Windows 7 64-bit PC as well.
