### ISSUE TITLE
Not compatible with RHEL7/Oracle Linux 7

### ISSUE THREAD

**Issue by kiview** [assetto-corsa-web/accweb#107]
When I try to run the `accweb` binary on Oracle Linux 7, I get the following error:

```
./accweb: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./accweb)
```

One possible workaround would be distributing accweb as a statically linked binary. Else, it is probably a good idea to mention the current incompatibility in the README.

**Comment by Kugelschieber** [comment]
accweb doesn't require any fancy libraries and glibc is the standard library of C, so you should have it installed usually.

**Comment by kiview** [comment]
It is installed, but in a different version (2.17), which is incompatible. This will be the same problem on all RHEL7 based distros (centOS, Oracle Linux), which are not that exotic.

**Comment by Kugelschieber** [comment]
I'll fix that in future versions. You can use this statically linked binary for now:

[accweb_1.11.2_patch.zip](https://github.com/assetto-corsa-web/accweb/files/5470828/accweb_1.11.2_patch.zip)

**Comment by kiview** [comment]
Thanks!
Not necessarily a high priority, just wanted to communicate my finding 🙂

**Comment by kiview** [comment]
Just FYI, I have the same problem in Ubuntu 20.04, did you change the dependencies recently?

**Comment by Kugelschieber** [comment]
No?

**Comment by kiview** [comment]
I am having this on newly set up Ubuntu 20.04 VM in Oracle cloud:

```
$ ./accweb
./accweb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./accweb)
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.1) 2.31
```
