### ISSUE TITLE
Server does not start once Entry List contains a team

### ISSUE THREAD

**Issue by kiview** [assetto-corsa-web/accweb#108]
After adding 2 drivers to a team, the server stops directly after starting. Log is minimal:
```
it looks like wine32 is missing, you should install it.
multiarch needs to be enabled first.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32"
```

Generated `entryList.json` looks like this (replaced real Steam IDs):
```
{
  "configVersion": 1,
  "entries": [
    {
      "drivers": [
        {
          "firstName": "",
          "lastName": "",
          "shortName": "",
          "driverCategory": 0,
          "playerID": "S4711"
        },
        {
          "firstName": "",
          "lastName": "",
          "shortName": "",
          "driverCategory": 0,
          "playerID": "S4712"
        }
      ],
      "raceNumber": -1,
      "forcedCarModel": -1,
      "overrideDriverInfo": 0,
      "isServerAdmin": 1,
      "customCar": "",
      "overrideCarModelForCustomCar": 0,
      "ballastKg": 0,
      "restrictor": 0,
      "defaultGridPosition": -1
    }
  ],
  "forceEntryList": 0
}
```

In addition, I can't remove a driver using the Remove Driver button in the UI anymore (only after saving).

**Comment by kiview** [comment]
@Kugelschieber Could you confirm that this is a bug and not a user mistake?
I also realized that I should try to start the server manually with the generated config, to maybe get additional log output.

**Comment by Kugelschieber** [comment]
I'm not sure if the configuration is correct or not. Does it start after you install wine32?

**Comment by kiview** [comment]
I always have this log error. I think it is related to the check not correctly identifying wine64 as compatbile. The server works in general without problems.

**Comment by Kugelschieber** [comment]
Strange. Well, most of this issues should sort out with v2, which hopefully is easier to maintain.

**Comment by kiview** [comment]
After some more debugging, I think I found the error. Once I changed the encoding of the file manually to UTF-16 using VIM, it works. This is in line with the server documentation:
> The server is exclusively configured via JSON files in UTF16-LE format. Using UTF8 file encodings may seem to work but will lead to wrong readings. 

I assume this might be a general issue for all generated config files so far?

**Comment by Kugelschieber** [comment]
Yes, that's a known bug.
