### ISSUE TITLE
Possible to call the API directly from an external application ? 

### ISSUE THREAD

**Issue by TheFreeman15** [assetto-corsa-web/accweb#117]
Thinking of doing some sort of integration with accweb and discord and wanted to know if it is possible to call the API routes directly from an external application?

Also, do you guys have a discord server?

**Comment by Kugelschieber** [comment]
Technically that's possible, but I will change the API with v2, so you might want to wait for that. You can join our Discord server here: https://discord.gg/Nz9Cgzwa
