### ISSUE TITLE
autostart

### ISSUE THREAD

**Issue by hamzalija** [assetto-corsa-web/accweb#119]
a suggestion:
if the server (hw) restarts for ie. maintinance. once the accweb is started then start the servers who are flagges as autostart maybe?

**Comment by DaStivi** [comment]
any news on this topic? v2 anywhere near on the horizon??

isn't there any easy option to enable some sort of autostart the accserver.exe after accweb starts? i've allready added accweb to systemctl as service and run in automatically..

**Comment by DaStivi** [comment]
> any news on this topic? v2 anywhere near on the horizon??
> 
> isn't there any easy option to enable some sort of autostart the accserver.exe after accweb starts? i've allready added accweb to systemctl as service and run in automatically..

nevermind, i'll found ah way... pretty sketchy but it works...

i'll ended up the following, created an accweb service in ubuntu:
`sudo vi /etc/systemd/system/accweb.service`

`[Unit]
Description=ACC Server Manager Web

[Service]
User=root
WorkingDirectory=/home/username/accweb_1.13.4/
ExecStart=/home/username/accweb_1.13.4/accweb
ExecStartPost=/home/username/accweb_1.13.4/start-accserver-exe.sh
Restart=always

[Install]
WantedBy=multi-user.target`

notice the _**ExecStartPost=/home/steve/accweb_1.13.4/start-accserver-exe.sh**_

the script basically just makes an rest api:
`#!/bin/bash
TOKEN=$(curl -s 'https://localhost:8080/api/login' --data-raw '{"password":"password in clear text"}' --compressed --insecure |  jq -r '.token')
curl 'https://localhost:8080/api/instance' -H  "authorization: Bearer $TOKEN" --data-raw '{"id":xxxxxxxxxxxx}' --compressed --insecure`

**Comment by pedrofaria** [comment]
released on 1.15.0 :)
