### ISSUE TITLE
Can the moderator edit the parameters of a server?

### ISSUE THREAD

**Issue by zenith464** [assetto-corsa-web/accweb#126]
Hi. I want to give access to a moderator so that he can modify parameters of a server, but I have seen that he can only start and stop it.

Is there any way that a moderator can change parameters of a server without giving him administrator permissions?

Thank you very much.

**Comment by Kugelschieber** [comment]
No sorry, if you want him to be able to edit servers, he needs to be an administrator.

**Comment by zenith464** [comment]
OK thanks. Is there any chance that this feature will be implemented in the future?

**Comment by Kugelschieber** [comment]
Maybe with version 2, but probably not.
