### ISSUE TITLE
trackTemp

### ISSUE THREAD

**Issue by kj5dpl** [assetto-corsa-web/accweb#133]
As far as I remember trackTemp parameter is obsolete.
But still works :-)
Could you please add it to configuration screen?

**Comment by Kugelschieber** [comment]
I don't know if I want to support "unofficial" features. It has a reason when Kunos removes something.

**Comment by Sefni** [comment]
To be honest it works from day 0. Also not sure if this is just the case on my side, but exent.txt is generating "trackTemp" anyway?

**Comment by kj5dpl** [comment]
> I don't know if I want to support "unofficial" features. It has a reason when Kunos removes something.
Yes you do :-)
And fans of your software will appreciate

**Comment by michalnow** [comment]
it would be awesome to see trackTemp parameter in gui. Cannot wait to see it !

**Comment by mstrychalski** [comment]
+1

**Comment by Kugelschieber** [comment]
https://github.com/assetto-corsa-web/accweb/releases/tag/v1.13.3
