### ISSUE TITLE
openssl download path

### ISSUE THREAD

**Issue by kj5dpl** [assetto-corsa-web/accweb#136]
openssl path used in go-rsh-keys.cmd
https://bintray.com/vszakats/generic/download_file?file_path=openssl-1.1.1d-win64-mingw.zip
does not exits
maybe:
https://curl.se/windows/dl-7.75.0_4/openssl-1.1.1j_4-win64-mingw.zip

**Comment by Kugelschieber** [comment]
Looks like it has been removed. Can you open a pull request?

**Comment by kj5dpl** [comment]
I cant open pull request v1 ????

**Comment by Kugelschieber** [comment]
Of course.
