### ISSUE TITLE
Can't change configuration file directly in config folder

### ISSUE THREAD

**Issue by CwTiruve** [assetto-corsa-web/accweb#139]
Hello, 

When I try to make some change directly in config folder (Like set a new entrylist file), 
it doesn't make change in webUI,
I don't know if it works in the server (can't test right now), but it will be good to see change in the WebUI

I'm on the Windows version.

**Comment by Kugelschieber** [comment]
You need to restart the server if you do that. The configurations are held in memory and are not loaded from disk every time you open the config.

**Comment by CwTiruve** [comment]
The accweb server ?
And so if I start the ACC server, it will load the configuration from disk ?

**Comment by Kugelschieber** [comment]
Yes, accweb. The game server itself will load the config from disk.

**Comment by CwTiruve** [comment]
Ok thank's! ;)
