### ISSUE TITLE
Just refresh and logout button present

### ISSUE THREAD

**Issue by paradizIscool** [assetto-corsa-web/accweb#14]
I only get No server found, refresh and logout button present, debug log says nothing special. What can I try?
Checked server path, changed keys

**Comment by Kugelschieber** [comment]
What browser do you use?

**Comment by paradizIscool** [comment]
Chrome
Tried IE, got a light grey screen

**Comment by Kugelschieber** [comment]
What does the browser log say? (F12 -> Console)

**Comment by paradizIscool** [comment]
[DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) 
on login page, nothing on main page

**Comment by paradizIscool** [comment]
accweb log

time="2019-06-11T13:39:52+02:00" level=info msg="Configure logging..."
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_ALLOWED_ORIGINS=*"
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_CONFIG_PATH=config/"
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_HOST=127.0.0.1:8070"
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_LOGLEVEL=debug"
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_SERVER_DIR=D:\\Assetto Corsa Competizione\\ACC\\server"
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_SERVER_EXE=accServer.exe"
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_TOKEN_PRIVATE_KEY=secrets/token.private"
time="2019-06-11T13:39:52+02:00" level=info msg="ACCWEB_TOKEN_PUBLIC_KEY=secrets/token.public"
time="2019-06-11T13:39:52+02:00" level=info msg="Loading build.js..."
time="2019-06-11T13:39:52+02:00" level=info msg="Loading server list..."
time="2019-06-11T13:39:52+02:00" level=info msg="Server list loaded successfully" servers=0
time="2019-06-11T13:39:52+02:00" level=info msg="Configuring CORS..."
time="2019-06-11T13:39:52+02:00" level=info msg="Starting server..."
time="2019-06-11T13:39:52+02:00" level=info msg="Using HTTP read/write timeouts" read_timeout=20 write_timeout=20
time="2019-06-11T13:40:42+02:00" level=debug msg="Decoded JSON request" req=&{##PASS##}

**Comment by Kugelschieber** [comment]
I can't tell why it's not working for you. I need someone else to confirm this as a bug.

**Comment by paradizIscool** [comment]
I was gone to the server page manually, no save button neither

**Comment by Kugelschieber** [comment]
Here is a screenshot from the latest version in FireFox 67:
![accweb_1 1 1](https://user-images.githubusercontent.com/6115423/59418729-cdab2880-8dc9-11e9-9d0b-7a220ce3a109.png)

**Comment by paradizIscool** [comment]
same without red button, firefox and chrome

**Comment by paradizIscool** [comment]
Could you give me a correct file to put in config folder to check that server will appear?

**Comment by Kugelschieber** [comment]
(Windows)
```
Rem Adjust this file to match your needs.

Rem sets host and port
Rem 80 is the default port for web servers and meight be blocked on your machine
Rem in that case, change it to anything else, e.g. 8080
set ACCWEB_HOST=0.0.0.0:8080

Rem IMPORTANT must be set, use strong different passwords for each
set ACCWEB_ADMIN_PASSWORD=admin
set ACCWEB_MOD_PASSWORD=mod
set ACCWEB_RO_PASSWORD=ro

Rem these files must exist
set ACCWEB_TOKEN_PUBLIC_KEY=secrets/token.public
set ACCWEB_TOKEN_PRIVATE_KEY=secrets/token.private

Rem create this directory in your installation directory
set ACCWEB_CONFIG_PATH=config/

Rem set the installation path of the ACC server
set ACCWEB_SERVER_DIR=C:\Program Files (x86)\Steam\steamapps\common\Assetto Corsa Competizione\server

set ACCWEB_LOGLEVEL=info
set ACCWEB_ALLOWED_ORIGINS=*
set ACCWEB_SERVER_EXE=accServer.exe

accweb.exe
```

**Comment by paradizIscool** [comment]
Not this one, a file created by the service in the config folder "ACCWEB_CONFIG_PATH=config/"
I guess the go script create json files in this folder to manage the instances.

**Comment by Kugelschieber** [comment]
configuration.json
```
{"udpPort":9600,"tcpPort":9600,"maxClients":10,"configVersion":1,"registerToLobby":1}
```

event.json
```
{"track":"monza","eventType":"E_6h","preRaceWaitingTimeSeconds":15,"sessionOverTimeSeconds":120,"ambientTemp":26,"trackTemp":30,"cloudLevel":0.3,"rain":0,"weatherRandomness":1,"configVersion":1,"sessions":[{"hourOfDay":9,"dayOfWeekend":1,"timeMultiplier":1,"sessionType":"R","sessionDurationMinutes":7}],"postQualySeconds":0,"postRaceSeconds":0}
```

settings.json
```
{"serverName":"Servername","password":"Password","adminPassword":"Admin","trackMedalsRequirement":0,"safetyRatingRequirement":-1,"configVersion":1,"racecraftRatingRequirement":0,"spectatorSlots":6,"spectatorPassword":"Spectator","dumpLeaderboards":0,"isRaceLocked":0}
```
