### ISSUE TITLE
OpenSSL.zip 

### ISSUE THREAD

**Issue by Munkeywaxx** [assetto-corsa-web/accweb#140]
Error is as follows when running gen_rsa_keys.
![unknown](https://user-images.githubusercontent.com/3329277/113291204-97b29d80-92ea-11eb-95a4-b9dbe901a553.png)

Windows Server 2012
Unrestricted admin access

Does the Server require the Main game and Libraries to be installed?
I'm thinking it's an issue with windows itself.

Thanks

**Comment by BertDuyck** [comment]
- Download the ssl zip from here [ https://mirror.firedaemon.com/OpenSSL/openssl-3.0.0.zip](url)
- Extract the zip to the root and keep the name openssl-3 for it.
- Right click gen_rsa_keys.cmd
- Replace complete script with this
```
@echo off

echo Creating secrets directory and keys
rd /S /Q secrets >NUL
mkdir secrets >NUL
openssl-3\x64\bin\openssl genpkey -algorithm RSA -out secrets\token.private -pkeyopt rsa_keygen_bits:4096 >NUL
openssl-3\x64\bin\openssl rsa -pubout -in secrets\token.private -out secrets\token.public >NUL
```

This worked for me.
