### ISSUE TITLE
Can only make servers with max of 24 drivers. 

### ISSUE THREAD

**Issue by mikeev261** [assetto-corsa-web/accweb#141]
Unsure if this is a problem with ACCweb, ACC, or my server config, but I can't seem to make a server with > 24 car slots. I have max car slots set to 50 and max connections set to 50. I don't remember having this problem in the past. Difficult to figure out when it started

![image](https://user-images.githubusercontent.com/4935661/113522838-cf7f4680-9571-11eb-9366-d6546894ea99.png)

Anything else I need to check? Anything I'm missing?

**Comment by Sefni** [comment]
is there a password? If not ACC will limit max number of players. Please check Server Admin Handbook, as this is not an issue within accweb

**Comment by mikeev261** [comment]
@Sefni apologies- I should have mentioned that: yes, I have a password on these servers (all of them). I've been running servers for over a year now and have yet to see this problem.
