### ISSUE TITLE
bop.json - incorrect name

### ISSUE THREAD

**Issue by Sefni** [assetto-corsa-web/accweb#143]
Hey, small issue while creating bop.json

The correct name for ballast is ballastKg the Kg is missing in bop.json and AC is not recognizing that. I believe code in server.go should look like that:

type BopSettings struct {
	Track      string `json:"track"`
	CarModel   int    `json:"carModel"`
	Ballast    int    `json:"ballastKg"`
	Restrictor int    `json:"restrictor"`
}

**Comment by pedrofaria** [comment]
the latest version of the source code seems to be correct
