### ISSUE TITLE
Entry List Remove Driver don't work

### ISSUE THREAD

**Issue by NichtDerBert** [assetto-corsa-web/accweb#144]
If i try to remove a Driver from Entry List it won't remove the driver.
after clicking the button "Remove Driver" nothing happens, driver is still in list. after saveing and reopening the editor driver also still in list.

**Comment by NichtDerBert** [comment]
got it fixed
after changing entry.vue as follow it works:
starting at line 106

```
removeDriver(index) {
    //index = parseInt(index);

    for(let i = 0; i < this.drivers.length; i++) {
        if(this.drivers[i].playerID === index.driver.playerID) {
            this.drivers.splice(i, 1);
            break;
        }
    }
}
```

**Comment by pedrofaria** [comment]
How I can reproduce the issue?

**Comment by Kugelschieber** [comment]
Hmm I think the index should be an integer and not an object. Maybe the driver gets emitted instead of the index for the entry.
