### ISSUE TITLE
Enhancement: Scheduled server restarts

### ISSUE THREAD

**Issue by ericwbentley** [assetto-corsa-web/accweb#145]
I run a few servers for our league where people can drop in whenever and practice. Some people have reported that when they join, the time of the sessions is way off and they ended up doing a night race when the race should be at 3pm.

Usually I can fix it by restarting the server, I'm guessing there is some issue with ACC servers being up for a long time that causes these issues. It would be nice to have an option to restart the servers automatically on a schedule so I don't have to restart them manually, for example restart every day at 2am.

**Comment by smaxx1337** [comment]
Hello,

I don't think this feature will be added because the maintainer of this project does not really have time to work on this project :(.

However, you can use the REST API of ACCWeb to restart the servers.

**Comment by Jovimpc** [comment]
I've worked arround this same issue, I created a "dummy" initial Free practice session with 1 muinute at the day one (friday) at 1am, this way the session that gets bugged its the first one, the other(s) are just fine, the only obvious downside is that you have to wait one minute to start the real session but you can use the time to load setup and one minute isn't very long anyway
