### ISSUE TITLE
Looking for Maintainers!

### ISSUE THREAD

**Issue by Kugelschieber** [assetto-corsa-web/accweb#152]
I want You! This is your chance to become a maintainer for a popular open-source project! I no longer have the time to work on this regularly, so if you care about accweb, please let me know below and I will add you as a maintainer.

**Comment by kj5dpl** [comment]
I am not experienced dev but interested in simracing so have some additional motivation. I could try

**Comment by pedrofaria** [comment]
I also don't have too much time, but as a acc player, accweb user and golang dev, I can help you and the project as well.

**Comment by Kugelschieber** [comment]
Awesome!

**Comment by BertDuyck** [comment]
I am already using your golang backend for a project and was already thinking the client could use some rework to handle state and make sure there are no conflicts, etc...
I am an angular frontend dev and I can have a look at the client as I was already going to start building another client for this API.

**Comment by Dpaganini** [comment]
Nice, i have interest but not so much time.
I´m a fullstack angular/node dev but works in what needs.
Maybe i can help the project

**Comment by Kugelschieber** [comment]
FYI I started reimplementing everything on v2, which is probably a good starting point to clean up/modernize accweb.

**Comment by mikeev261** [comment]
I'm a hardware developer who knows some python. So I'm probably not the best fit, but I love this project and would be willing to try to carve out some time to learn Go for this. Time will be super limited though.

**Comment by Kugelschieber** [comment]
Awesome! I'll add you too :)

**Comment by kj5dpl** [comment]
@Kugelschieber is there any space dedicated for maintainers already ?  I am thinking of making ACC 1.8 changes but don't want to double the work if somebody already working on it ?

**Comment by Kugelschieber** [comment]
No, there is none. You can use the discord to coordinate.

**Comment by pedrofaria** [comment]
Can you share the discord link??? lets align next steps and define a plan

**Comment by Kugelschieber** [comment]
Oh, I think I'm got confused and there is no Discord server, or I'm no longer on it. But I'm pretty sure we had one... hmm.

**Comment by pedrofaria** [comment]
it was the https://github.com/assetto-corsa-web/accweb/discussions ???

**Comment by Kugelschieber** [comment]
Not sure what you mean, but the discussion section is also a good place for coordination. I would keep it on GitHub.

**Comment by praboy** [comment]
I'm interested in maintaining the project. Can you update the discord link?

**Comment by praboy** [comment]
A Discord server would be nice :)

**Comment by pedrofaria** [comment]
I just created one... please join and help me to setup it... https://discord.gg/9AfC5ST9

**Comment by BertDuyck** [comment]
@pedrofaria is the discord removed again? 
![image](https://user-images.githubusercontent.com/17513304/144602016-2db4ddfe-75bf-414b-9063-a9099c7d7e12.png)

Something else, 
I would start to create a client for acc-web
I work in angular as my preferred framework. But I am not sure if we want to keep this client as vue or go with another here?
Is there anybody else willing to work on the client with certain preferences?

**Comment by itsmylife44** [comment]
> @pedrofaria is the discord removed again? ![image](https://user-images.githubusercontent.com/17513304/144602016-2db4ddfe-75bf-414b-9063-a9099c7d7e12.png)
> 
> Something else, I would start to create a client for acc-web I work in angular as my preferred framework. But I am not sure if we want to keep this client as vue or go with another here? Is there anybody else willing to work on the client with certain preferences?



https://discord.gg/vA34DMA7

**Comment by pedrofaria** [comment]
I didn't know that this link can expire....

https://discord.gg/AVWdF56t6c

this one is forever and ever!

**Comment by pedrofaria** [comment]
Hey @Kugelschieber , may I ask you to add @matslindh  as maintainer as well?

**Comment by Kugelschieber** [comment]
Sure!

**Comment by vexersa** [comment]
I'm interested! Please add me :)

**Comment by matslindh** [comment]
@vexersa We have a Discord server available at https://discord.gg/AVWdF56t6c and any PRs can be submitted for review - it's currently a short distance from making contributions to getting them in a release. :-)
