### ISSUE TITLE
Update Tracks for 2021 BoP and CarID for Entrylist

### ISSUE THREAD

**Issue by Bloodsaw** [assetto-corsa-web/accweb#153]
Kunos released a new BoP with new Car ID and they removed the choice of track Season.
They call it "Open Season" so that always the newest given BoP for a track is applied. 

X.161.8.0
- Updated car groups (Cup, ST is merged to GTC)
- Removed all “_2019”, “_2020”, “_2021” track suffixes, please just use the track name in any configuration now
- Added the BMW M4 GT3 entry

[ServerAdminHandbook.pdf](https://github.com/assetto-corsa-web/accweb/files/7596510/ServerAdminHandbook.pdf)

It would be very helpful if this change could be implemented here too.
-Removing all season suffixes from tracks
-Removing CUP category choice CUP and ST
-Adding GTC category
-Adding BMW M4 car for entry list

Thanks in advance.

**Comment by kj5dpl** [comment]
I am working on it
