### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by Kugelschieber** [assetto-corsa-web/accweb#16]

**Comment by gillesdubois** [comment]
Hi @Kugelschieber ,

I'm using your tool for some time now and I would like to know if you need help on docker implementation ?
I already use a docker image based on you software, its just a really specific one. I could adapt it to be more generic and create pull a request, what do you think ?

Regards,
Gilles Dubois.

PS : Nice work, really appreciate having such an amazing tool

**Comment by Kugelschieber** [comment]
Hey Gilles, that sounds awesome! Go ahead and create a pull request if you like :)
