### ISSUE TITLE
Version not updated?

### ISSUE THREAD

**Issue by hrdejong** [assetto-corsa-web/accweb#162]
Replaced all with the latest 1.14 release but accweb says "accweb Version 1.13.4". Some error on my side or was the version not updated in the code?

**Comment by Jovimpc** [comment]
I have the same issue, so it's not on your side.
Also I've found a change log for 1.14.2 but can't find the realease anywhere. Sorry but i'm kind of a noob here. and i feel that's no need to open a new issue for this.

**Comment by pedrofaria** [comment]
which kind of issues you are facing?

**Comment by Jovimpc** [comment]
> which kind of issues you are facing?

In the changelog the 1.14.2 is mentioned but I can't find that release.

**Comment by Kugelschieber** [comment]
https://github.com/assetto-corsa-web/accweb/discussions/163

**Comment by pedrofaria** [comment]
fixed with version 1.14.3
