### ISSUE TITLE
Can't install it on Win, any can help?

### ISSUE THREAD

**Issue by giac0dex** [assetto-corsa-web/accweb#164]
Hello, any can help me to install it on Win?
i can't i dont know why, maybe some video? 
i have see a video about install accweb but is very old and is no the same
thanks in advance

**Comment by giac0dex** [comment]
i get this error after start a server (server get closed after some seconds)
![image](https://user-images.githubusercontent.com/86849086/148132235-339299ea-c840-47b1-98ef-7f208250cafd.png)

**Comment by realemx** [comment]
You can access the web interface, right? There's a button on the server list to show the log output of the server. That would be helpful. 
But my wild guess: You are running the server on your private network and have "Register to Lobby" enabled. In this case the ACC Lobby Server can't connect to your Server. If you want to host a public server, then you have to open the ports you've configured in your router. (And also have a publicly reachable network to begin with). If you do only want to host a local server, just disable the registration to lobby and active the "LAN discovery" option below it.
