### ISSUE TITLE
Server won´t start

### ISSUE THREAD

**Issue by GitTech4K** [assetto-corsa-web/accweb#169]
Hello,

I have tried to install accweb on my Windows computer. But it won´t start.

I´ve got the message, that the server starts, but nothing happend after some minutes. 

Can you help me with this issue?

I attach a picture from the cmd.
![accweb_Error](https://user-images.githubusercontent.com/71223614/150647571-ffcd5e5b-caee-4c57-a07a-0c068bddfa21.JPG)

**Comment by pedrofaria** [comment]
accweb is running.... access the interface with your browser... the address is defined in the config file...
