### ISSUE TITLE
The server does not shut down

### ISSUE THREAD

**Issue by Cele91** [assetto-corsa-web/accweb#172]
I'm noticing a strange panel problem. The server starts but does not shut down if click on STOP. It stays on.

My machine is a VPS with UBUNTU 21.10 with WINE7.0
![Immagine](https://user-images.githubusercontent.com/9697979/151148063-4f9f524b-7d52-44fb-896a-81651010b662.png)

Thanks at all

**Comment by pedrofaria** [comment]
Hi @Cele91 ,

Can you check the error log content in the server config path?
