### ISSUE TITLE
Passwords do not save or frontend does not signify that a password exists

### ISSUE THREAD

**Issue by vexersa** [assetto-corsa-web/accweb#186]
Passwords do not appear to save in the passwords field when saving a server. 

V1.6.1

Recreate: 

1. Create/edit server
2. Add password
3. Click save
4. Open server config
5. Password is not shown as being set

**Comment by pedrofaria** [comment]
actually the server password is being saved but just not being displayed... I can agree with you that the user experience isn't really good for the server pwd... I will try to find a way to improve this ... thanks for the report!

**Comment by vexersa** [comment]
Awesome!

**Comment by pedrofaria** [comment]
This fix was released :)
