### ISSUE TITLE
Replace gen_rsa_* scripts with go native functionality

### ISSUE THREAD

**Issue by matslindh** [assetto-corsa-web/accweb#188]
The gen_rsa_keys scripts (in particular on Windows where it downloads an openssl file from the web and runs the embedded `openssl.exe`) assumes that certain functionality is available and present.

Go supports the required functionality to embed this into the application (or as a utility function) instead, making the external dependencies unnecessary.

https://gist.github.com/sdorra/1c95de8cb80da31610d2ad767cd6f251
https://stackoverflow.com/questions/64104586/use-golang-to-get-rsa-key-the-same-way-openssl-genrsa

.. seems like a decent references for how to implement this in Go, but I'm a bit ware about changing how anything touching crypto works - but can't evaluate that the current solution is any better either.

**Comment by pedrofaria** [comment]
this is a really good idea...
