### ISSUE TITLE
Server won’t stop properly with GUI. 

### ISSUE THREAD

**Issue by roubochr** [assetto-corsa-web/accweb#205]
I understand that Linux isnt fully supported but just wondering if there is a fix/workaround for this issue I’m facing. I can’t stop servers from the web GUI properly. The server says stopped but the stop button doesn’t go green again and change to start.

**Comment by dinuxlt** [comment]
What I found, this happens from wine 6.5 and up

**Comment by roubochr** [comment]
That did the trick! Thanks heaps @dinuxlt
