### ISSUE TITLE
End of line change in release 1.4.0

### ISSUE THREAD

**Issue by dam09fr** [assetto-corsa-web/accweb#21]
Hello,

In release 1.4.0 it seems that EOL is now CR+LF (Windows style), instead of LR (Unix style) in previous.

My docker builds are not working anymore ...
Did you do that for a specific reason ?

Thank you in advance for your answer.

![Screenshot](https://nsa40.casimages.com/img/2019/07/15/190715060502497801.jpg)

**Comment by Kugelschieber** [comment]
Hmm no? If I try to convert the line ending it doesn't show any changes. Git is configured to convert line endings as well. So they should be correct on GitHub. How do you build the docker image? Locally?

**Comment by dam09fr** [comment]
It's not with git configuration because I use binary files you provide throught Github release section:
https://github.com/assetto-corsa-web/accweb/releases/download/1.4.0/accweb_1.4.0.zip
Line ending have changed in 1.4.0.

**Comment by Kugelschieber** [comment]
I've updated the zip fo 1.4.0. Can you check again?

**Comment by dam09fr** [comment]
accweb Version 1.4.0 is up and running on my server !
Thanks ;-)

**Comment by dam09fr** [comment]
Hello, I'm re-opening this issue because I'm having the same issue with release 1.6.0
So my docker env is no more working.
Can you help please ?
Thanks in advance

**Comment by Kugelschieber** [comment]
Yeah this happens when I build on windows on my workstation at work. Try 1.6.1 that was build on Ubuntu at home.

**Comment by Kugelschieber** [comment]
Btw you can try to run dos2unix on it, which should repear the broken line endings.

**Comment by dam09fr** [comment]
Thanks a lot, I'll implement dos2unix in my Dockerfile for the next builds.
