### ISSUE TITLE
1.18.0 | Start the Server Instanz will not copy the accserver.exe

### ISSUE THREAD

**Issue by SixEcho84** [assetto-corsa-web/accweb#219]
Hello,

since 1.18.0 the accserver.exe is not copy from acc folder to config folder after start a server Instanz.
accWeb must be complete restarted to pull the new accserver.exe into config for each Instanz.

i'm using Linux Alpine.

greetings
Daniel

**Comment by pedrofaria** [comment]
Hello Daniel, 

The PR #220 will fix this issue and will be released in v1.19.0.
