### ISSUE TITLE
Driver swap crashes using accweb

### ISSUE THREAD

**Issue by stonith** [assetto-corsa-web/accweb#227]
I've confirmed that accweb has a bug that causes driver swaps to crash the game client, when I create a server using another tool it doesn't crash. I haven't had time to to test whether it's just the entrylist itself since it requires two people to test. However, I've attached the entrylist file(entrylist.json) created by accweb and another tool that works(entrylist.txt).

 
[entrylist.zip](https://github.com/assetto-corsa-web/accweb/files/9772157/entrylist.zip)

**Comment by stonith** [comment]
I tried copying the entrylist.txt file into the server instance directory (deleted entrylist.json) and manually ran accserver.exe myself, however the driver swap still crashes the game. It seems that the problem isn't the entrylist itself but somewhere else.

**Comment by StingerTopGun** [comment]
@stonith i'm having the same problem, have you ever found a solution?

**Comment by mrpbdy** [comment]
Very odd - we've had 2 x 48 car x (3/4 drivers) x >10hr races in the last month and we've had no issues at all

**Comment by mrpbdy** [comment]
@stonith Windows.

**Comment by alotufo** [comment]
@stonith I know this is an old thread, but I had this same issue with driver swap, and through some testing I found that having the setting of tyreSetCount to 0 in eventRules.json crashes it. I changed mine to 50 and no more crashing on driver swap.

**Comment by alotufo** [comment]
I believe the line to be changed to default to 50 is:

https://github.com/assetto-corsa-web/accweb/blob/fd887405dfb9e6509d059fdfa07066b02bb452f8/public/src/components/server_config/eventrules.vue#L40

**Comment by stonith** [comment]
Nice catch!

**Comment by alotufo** [comment]
@StingerTopGun in case you were still looking for a fix I'll mention you too

**Comment by pedrofaria** [comment]
merged!
