### ISSUE TITLE
when logged in as a guest, "Online" text is almost unreadable

### ISSUE THREAD

**Issue by Blumlaut** [assetto-corsa-web/accweb#247]
The default text seems to be a shade of grey which is almost unreadable on most devices:
![grafik](https://github.com/assetto-corsa-web/accweb/assets/13604413/1c71830d-6c1d-48d5-bf6d-b759c7a244ce)

I did not create a PR as styling like this is usually personal preference, but i tweaked the CSS to
```
background: #17a802;
color: white;
```
on my end, and readability for the status text has improved massively:
![grafik](https://github.com/assetto-corsa-web/accweb/assets/13604413/35b0a6bc-dde9-4c03-bff4-d43d05983cf1)

**Comment by pedrofaria** [comment]
Will be fixed in the next release.... thanks!
