### ISSUE TITLE
Version 1.22.0 is FULL of bugs!! It's awful

### ISSUE THREAD

**Issue by Fedemarley** [assetto-corsa-web/accweb#257]
So, I recently installed the lastest 1.22 version on my two VPS Linux servers, and I immediately started noticing these bugs:

- Unable to stop servers. I have to ssh into the remote server and stop accWeb altogether. very unconvenient.
- The servers keep being listed as "not registered" in the View Live page, even though they are perfectly running and visible on the server browser. Very frustrating.

Hoping to see these issues resolved asap. Thanks. I may have to revert to old 1.20.1 version which was much more stable.

**Comment by pedrofaria** [comment]
That wasn't a good start...

Being disrespectful doesn't work here. No one receives, or has received, a single cent to create and maintain this project. Everyone has their own job and only contributes to the project in their free time and only when they can. If you're not happy, I don't give a shit! Anyway, I give you three options:

1) Choose another dedicated server manager that is better.
2) As it is an open-source project, contribute! find the problem, fix it and send your pull request with the fix. (RECOMMENDED!)
3) Search the github issue listing to see if anyone has already reported the same issue as yours. If you don't find it, open a new one and be friendly.

Peace!

**Comment by kslen** [comment]
It's Wine, not so much accweb, though accweb needs a slight change to its source to circumvent the issue. See https://github.com/assetto-corsa-web/accweb/issues/249 for a workaround and possible solution if you're handy with GO. :)

**Comment by kslen** [comment]
Just wanted to take the opportunity to inform that the issue has been resolved by the lead dev. New version is on its way. :)
