### ISSUE TITLE
Log output wrong logs (after clone?)

### ISSUE THREAD

**Issue by drfugazi** [assetto-corsa-web/accweb#26]
Hi,
I cloned configuration from one server to another, then changed settings. When I start the server and want to check the logs, the output window shows wrong logs. The server log file in config directory is fine, so I don't know where are the output from. See screenshots.
![bug1](https://user-images.githubusercontent.com/8039533/68942418-d9e84700-07a8-11ea-8d73-d1700048efd9.JPG)
![bug2](https://user-images.githubusercontent.com/8039533/68943059-69dac080-07aa-11ea-9adb-c0ea5b66d73c.JPG)
![bug3](https://user-images.githubusercontent.com/8039533/68943067-6d6e4780-07aa-11ea-96e7-1f31eb3a6ee2.JPG)

**Comment by Kugelschieber** [comment]
The old log might have been copied. I'm not sure right now.

**Comment by drfugazi** [comment]
Logs are ok in log subdirectory of this config, you can open them with notepad, but browser gets old or blank content and Refresh won't help, restart either.
