### ISSUE TITLE
Negative BOP ballast not not being applied

### ISSUE THREAD

**Issue by arelstone** [assetto-corsa-web/accweb#260]
**[tldr;]**
After applying the LFM bop I've discovered that cars where the ballast is a negative number gets changed to 0 when starting the instance from accweb and manually starting accServer.exe. Running the accServer.exe on my own computer, all ballast is being applied correctly. Only difference is the encoding of the config files.

### Description
I've encountered an issue when trying to use LFM BOP which uses negative numbers for ballast it get's changed to 0 when when starting the server.

In the following I will refer the the server that hosts out accweb instance as **Patty**. I will refer to my own local computer as **localhost**

I've added a bop.json file thru the GUI and started the server instance. In the logs it shows that the ballast that should be a negative value - any negative value - is not being applied. Instead it's changes to 0.

Extracted from bop.json
```json
    {
      "track": "hungaroring",
      "carModel": 31,
      "ballastKg": 18
    },
    {
      "track": "hungaroring",
      "carModel": 8,
      "ballastKg": -40
    }
```

server.log on Patty
```txt
0:     Bop: carmodel 31 B:18|R:0 for track hungaroring  <- Correct
0:     Bop: carmodel 8 B:0|R:0 for track hungaroring <- Bentley 2018. Should be -40
0:     Bop: carmodel 20 B:0|R:0 for track hungaroring <- AMR V8 Vantage should be -23
0:     Bop: carmodel 30 B:9|R:0 for track hungaroring   <- Correct
0:     Bop: carmodel 32 B:19|R:0 for track hungaroring  <- Correct
0:     Bop: carmodel 21 B:0|R:0 for track hungaroring <- Honda NSX GT3 Evo should be -17
0:     Bop: carmodel 33 B:18|R:0 for track hungaroring  <- Correct
0:     Bop: carmodel 35 B:20|R:0 for track hungaroring  <- Correct
0:     Bop: carmodel 25 B:0|R:0 for track hungaroring <-    Mercedes-AMG GT3 should be -3
0:     Bop: carmodel 34 B:12|R:0 for track hungaroring  <- Correct
0:     Bop: carmodel 24 B:0|R:0 for track hungaroring <- Ferrari 488 GT3 Evo should be -20
```

After this I tried starting the accServer.exe manually by not using the GUI. The same happened. All negative ballasts was set to 0.

Next thing I tried was running an instance with the same content of the `bop.json` file on my localhost. To my surprice the ballast was set correct to -40 for carmodel 8.

Exact same bop.json, entrylist.json etc..

server.log on localhost
```txt
Bop: carmodel 31 B:18|R:0 for track hungaroring
Bop: carmodel 8 B:-40|R:0 for track hungaroring
Bop: carmodel 20 B:-23|R:0 for track hungaroring
Bop: carmodel 30 B:9|R:0 for track hungaroring
Bop: carmodel 32 B:19|R:0 for track hungaroring
Bop: carmodel 21 B:-17|R:0 for track hungaroring
Bop: carmodel 33 B:18|R:0 for track hungaroring
Bop: carmodel 35 B:20|R:0 for track hungaroring
Bop: carmodel 25 B:-3|R:0 for track hungaroring
Bop: carmodel 34 B:12|R:0 for track hungaroring
Bop: carmodel 24 B:-20|R:0 for track hungaroring
```

After a bit of digging and a comment by RG on discord made me check the file encoding. And that's the only difference I could find. Patty uses UTF16 and localhost uses UTF8.

Encoding on localhost
![image](https://github.com/assetto-corsa-web/accweb/assets/1322047/c1fe2df8-32a0-4013-95ef-04d16de463ca)

Encoding on Patty
![image](https://github.com/assetto-corsa-web/accweb/assets/1322047/70cd1178-86f4-4dfa-b479-34c005661e74)

I know that Kunos uses UTF16 for the result files. I'm suggesting that the config files will be encoded with UTF8 instead of UTF16.

**Comment by kslen** [comment]
Hi there, arelstone.

Have you tried enclosing the bop values with "-20" or to escape the - character with a leading \? Example: \-20

If memory serves me right, just using "-20" should resolve the issue.

**Comment by arelstone** [comment]
I switched back to Open Game Panel, where it works. Great job though guys
