### ISSUE TITLE
Player not visible in API data on double connection

### ISSUE THREAD

**Issue by Renegade89** [assetto-corsa-web/accweb#264]
As mentioned in the Discord 29th of november (15:39) by RS 

When a player connects with the same Steam ID and same car model the player is not visible anymore in the API data

From server log : 

```
New connection request: id 2092 Cody Gray S76561198050000000 on car model 23
New connection request: id 2119 Cody Gray S76561198050000000 on car model 23

Recognized reconnect: carId 1082, carModel 23, raceNumber #22
```

No issues when a player switches car model of course

**Comment by Renegade89** [comment]
Got this bug again yesterday. 

`
	Rule 470: New connection request: id 5 Konstantin Cherepanov S76561199471802383 on car model 22
	Rule 891: Late lastUdpPaketReceived for connId 5: 2253 ms (Konstantin Cherepanov)
	Rule1201: New connection request: id 8 Konstantin Cherepanov S76561199471802383 on car model 22
`

This McLaren was not visible in the live timing, but appeared in the ACCRC tool

![IMG_20240201_175326](https://github.com/assetto-corsa-web/accweb/assets/100537299/0149865d-c4c2-4062-bfe4-8b7619c280d6)
![IMG_20240201_175334](https://github.com/assetto-corsa-web/accweb/assets/100537299/cac48de5-12c4-4c6b-a292-424bcf74842b)

**Comment by pedrofaria** [comment]
this is hard to reproduce... but I guess I found the issue... I made some changes and will be in the next release...
