### ISSUE TITLE
Importing bop.json files to cloned ports fail, while newly created ports succeed.

### ISSUE THREAD

**Issue by kslen** [assetto-corsa-web/accweb#266]
**Environment:**
- ACCWeb 1.22.2
- ACCServer.exe current as of writing (nightly auto-update)
- Debian 12.4

**Description:**
When cloning a port in ACCWeb and importing a correctly encoded bop.json file, the ACCWeb interface displays the entries correctly. However, upon joining the server, the BoP is not applied. The server logs indicate that the bop.json is either blank or non-existent during startup, even though it has been confirmed to exist. This anomaly is specific to bop.json, as other JSON files are successfully read from the correct directory for any given port.

**Observations:**
- ACCServer.exe does not seem to recognize that the bop.json file is present.
- The issue is not present when creating a brand new port and importing the bop.json file, suggesting a potential problem with cloned ports.
- Successful tests with both positive and negative ballast have been conducted on new ports.
- The problem persists across multiple cloned ports, indicating a pattern.

**Hypothesis:**
There may be a bug in ACCWeb, specifically related to the handling of bop.json in cloned ports. I speculate that ACCWeb might be referencing the numerical directory ID of the original port, causing the failure to apply BoP. This is supported by the fact that a new port, not a clone, successfully applies BoP after importing a bop.json file.

**Reproducibility:**
The issue has been replicated on three new ports, consistently producing the same result.

**Workaround:**
To successfully import and apply BoP via import, it is recommended to create a new port rather than cloning an existing one. Exporting a cloned ports config in its entirety and then importing it to a new one, would be the quickest way to circumvent the problem and has been verified to work. This includes the bop.json which was exported and verified to be identical to what was initially imported, and cause no further issue when imported again to the new port.

**Additional Note:**
While the problem persists, successful application of BoP is observed in cloned ports when manually entered through the ACCWeb GUI.

**Comment by Bloodsaw** [comment]
Is this Bug still there? 
@pedrofaria mentioned that it's fixed in #267. Do we need to tests this again?

Steps to reproduce should be:
1. Create Server
2. Create or Upload a bop.json 
3. use "Copy config" to create a second server

Or am I misinterpreting something?

**Comment by pedrofaria** [comment]
We can close... I just followed this steps and its working
