### ISSUE TITLE
accweb.exe is not recognised

### ISSUE THREAD

**Issue by axeMaltesse** [assetto-corsa-web/accweb#27]
Hi there,

I have a really weird issue while I am trying to run start.cmd Basically at the end of the line it is not able to detect the accweb app and therefore it is not able to run the server. 

I was trying to hcange the location of the parent folder but it doesn't solve the issue. There is a SC:
![image](https://user-images.githubusercontent.com/14835119/70111367-f6e19e80-161f-11ea-81d0-58af9fc6ca8a.png)

I don't know if it matters but it seems like main is set for "/" while on Windows there is "\\".

**Comment by Kugelschieber** [comment]
Hmm I not so much into Windows. The slashes shouldn't be a problem.
Could you solve it yet?

**Comment by axeMaltesse** [comment]
My friend sent me his zip file and it works fine. I have no idea where was the problem, as I have cloned 6.1 and earlier versions previously. 
So it works fine now, but the issue is still unknown :)
