### ISSUE TITLE
Player name not visible when using 'special' lastName

### ISSUE THREAD

**Issue by Renegade89** [assetto-corsa-web/accweb#270]
Found a small bug after testing with a hack to display team names on a new line in the players name.

See this thread for the hack; https://www.assettocorsa.net/forum/index.php?threads/how-to-show-the-team-name-in-the-driver-list.73393/#post-1229315

In my entrylist.json I'm using this syntax:

`"lastName": "Lastname \nTeamname",`

In the live view the driver doesn't show up. Probably because of the \n in the last name. A problem escaping that \ character ?

**Comment by pedrofaria** [comment]
I could reproduce the issue but This will be not possible for accweb

<img width="527" alt="image" src="https://github.com/assetto-corsa-web/accweb/assets/9825/7a3ce853-6dc8-4abb-8dd2-5d31a52cd5cc">

As you can see, accserver.exe output with break line as well , and accweb parser depends on the break line to understand when the output line finish ... as we need the full line of a new connection to underrstand  when someone join the server, accweb will add the car, but not the driver... 

Sorry, but for now, there is no way to handle this.... but if you dont need the live data, accserver.exe will work as expected
