### ISSUE TITLE
Support for New DLC?

### ISSUE THREAD

**Issue by Menteroth** [assetto-corsa-web/accweb#33]
Would be great if support for tracks from the Intercontinental GT Pack DLC would be added to setup servers with.

- Kyalami Grand Prix Circuit (South Africa)
- Suzuka Circuit (Japan)
- Weathertech ®️ Raceway Laguna Seca (USA)
- Mount Panorama Circuit (Australia)

Great work anyhow.
Thanks in advance.

**Comment by Menteroth** [comment]
I added the new tracks in the build.js myself.

Track IDs.
```
kyalami_2019
suzuka_2019
laguna_seca_2019
mount_panorama_2019
```

**Comment by Kugelschieber** [comment]
The tracks have been added already. The new release is just not out yet.

**Comment by Menteroth** [comment]
Ah okay then. Well, got it sorted already hehe.

Thanks for making this nice web interface.
