### ISSUE TITLE
Next update

### ISSUE THREAD

**Issue by cestcomi** [assetto-corsa-web/accweb#40]
I'm sorry to speak here, but is the project still being followed and can we expect an update soon?
We have even more parameters which have been added via the "assistRules.json" file.
The latest ServerAdminHandbook is in version 7c.
Thank you.
[ServerAdminHandbook_v7c.pdf](https://github.com/assetto-corsa-web/accweb/files/4271960/ServerAdminHandbook_v7c.pdf)

**Comment by Kugelschieber** [comment]
Yes I'm still taking care of this project, but don't have time to do so frequently. Thanks for the update!

**Comment by cestcomi** [comment]
Thank you for your answer and the job already made.
I understand the lack of time.
And thanks for the answer on Kunos Forum:
[https://www.assettocorsa.net/forum/index.php?threads/release-accweb-assetto-corsa-competizione-server-management-tool-via-web-interface.57572/page-11#post-1120287](https://www.assettocorsa.net/forum/index.php?threads/release-accweb-assetto-corsa-competizione-server-management-tool-via-web-interface.57572/page-11#post-1120287)
I hope someone will help you to maintain this project.
Cheers.
