### ISSUE TITLE
Auto results

### ISSUE THREAD

**Issue by AUSNZ** [assetto-corsa-web/accweb#42]
Hi! Great job you are doing. Thankyou very much for all your efforts,  any chance of adding another menu so we can auto load results as well would be much appreciated. Thankyou eg..
![auto_upload](https://user-images.githubusercontent.com/57167683/76121533-f48c4780-6047-11ea-867e-0822bc38f54d.PNG)

**Comment by Kugelschieber** [comment]
That's a duplicate of this ticket: https://github.com/assetto-corsa-web/accweb/issues/3
