### ISSUE TITLE
Can't Copy 'config' folder to New Version

### ISSUE THREAD

**Issue by Menteroth** [assetto-corsa-web/accweb#49]
My current servers don't have bop.json and can't start the program because of it.

```
time="2020-04-10T14:39:33+02:00" level=fatal msg="Error loading server settings" error="open config\\1581095496\\bop.json: Det går inte att hitta filen." name=1581095496
```

**Comment by Kugelschieber** [comment]
https://github.com/assetto-corsa-web/accweb#version-180

**Comment by Menteroth** [comment]
Yeah. I saw it was added, but why does it need to exist? I don't feel like importing all my different server setups. That's gonna take too long.

**Comment by Kugelschieber** [comment]
@cestcomi implemented this. I'm not aware of the actual server configuration. I guess you can create that file by hand once?

**Comment by Menteroth** [comment]
But it seems to be looking in the server ID folder. Doesn't that mean it will look through every server's folder for that file? I guess I can create and copy paste into each folder. That's quicker at least.

**Comment by Kugelschieber** [comment]
Usually accweb creates that file. But if you're upgrading from a previous version you need to do that once or you delete the config directory (and lose all server configurations).

**Comment by Menteroth** [comment]
Yeah. I saved a backup from previous mistake when I had like three servers hehe.
I'll try this.

**Comment by Menteroth** [comment]
Yeah. Gotta copy bop and assistRules into each folder. That works.
