### ISSUE TITLE
BaseUrl support

### ISSUE THREAD

**Issue by david-maus** [assetto-corsa-web/accweb#5]
Hi,

is it possible to add a variable for a BaseUri? So for example, instead of xxx.xxx.xxx.xxx/ the app is working under  xxx.xxx.xxx.xxx/accweb/ ?

I have some problems with my nginx reverse proxy. It doesnt load the js, css ressources.

Or maybe some tipps for a proxy setup?

```
location /ACCWEB/ {

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_pass http://xxx.xxx.xxx.xxx:8080/;
}
```

**Comment by Kugelschieber** [comment]
You're right I haven't set the base in index.html. You can do that by modifying the public/index.html for now. Add `<base href="/" />` inside the `<head>` part:
```
<!DOCTYPE html>
<html>
<head>
    <base href="/" />
    <meta charset="utf-8" />
[...]
```

I'll add it to the next release.

**Comment by david-maus** [comment]
Hi,

if i set this to "/ACCWEB/" i can reach the app at xxx.xxx.xxx.xxx/ACCWEB/ but it doesn't load the resources. The links to the favicon etc. are correct i think but it doesn't load it. I think it returns the index?

**Comment by Kugelschieber** [comment]
Does it work if you set it to "/"? accweb serves all web content out of the `public` directory but the frontend is now looking for ACCWEB/public. If that doesn't work I'll have to add a new configuration variable for it.

**Comment by Kugelschieber** [comment]
Yeah every request coming from /ACCWEB/... must be rewritten to localhost:8080/ so that accweb can serve the files correctly. You can try figuring out how to do that with nginx and I'll add it to the configuration.

**Comment by david-maus** [comment]
Ok, a little update:

I switched to the subdomain option with a clean .conf because there is no extended URL/Directory:

```
server {

    listen 443 ssl http2;
    server_name acc.gef-gaming.de;

    root "/www/acc.gef-gaming.de/";

    include resty-server-https.conf;
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
    resolver 127.0.0.11 valid=30s;

    location / {

        proxy_pass http://127.0.0.1:8080;

        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_read_timeout      90;
        proxy_redirect          http://127.0.0.1:8080 https://acc.gef-gaming.de;

    }
    

}
```
Without setting the HTML BaseURl setting.


On editing/trying out this option i think i have found one main issue with my nginx settings:

I cleared all my caching/header/expire settings from the config file and then it was working (I dont know why this was an issue, most of the stuff was not related to the proxy location). I tested the URL/Directory option for a minute and it was working, too. Well, it gave an error because your backend couldn't find the correct url (I think with setting the baseurl again it is maybe working) but the css, js, favicon was working.

But i think an option for a real BaseUrl would be great in the future. Maybe an Env-Variable and the whole app is working from a directory like http://127.0.0.1:8080/accweb/ with auto redirect if you call http://127.0.0.1:8080 in your browser.

Anyway, thanks for your great work! :)
