### ISSUE TITLE
Assists rules settings are loaded on edit

### ISSUE THREAD

**Issue by dam09fr** [assetto-corsa-web/accweb#50]
Hello,
Sorry I dont have a lot of time to fix this myself these days ...
I noticed that since I upgrade to 1.9.0 the settings of the new "Assists rules" section are not loaded at next edit time causing frequent reset to default values when I change others settings.
Thanks in advance.

**Comment by dam09fr** [comment]
I confirm that the data is saved on the file, but if I edit the server, previous data is not set in the form and reset to zero. I was not able to find why ... any idea ?

**Comment by dam09fr** [comment]
@Kugelschieber do you have any idea where I can search ?
I've looked the code again and again without finding why ...

**Comment by Kugelschieber** [comment]
Well I always start by making sure the server returns the expected result and it is set throughout the components up to the one you need it in. You can do that by adding some console.logs along the way.

**Comment by Kugelschieber** [comment]
Fixed.

**Comment by dam09fr** [comment]
@Kugelschieber Thanks a lot for fixing it, i didn't find the time to work on it these days.

**Comment by Kugelschieber** [comment]
No problem, it was just a typo here:
```
this.$refs.assistrules.setData(r.data.assistrules);				
this.$refs.assistrules.setData(r.data.assistRules); // Rules...
```
