### ISSUE TITLE
Log Output

### ISSUE THREAD

**Issue by Menteroth** [assetto-corsa-web/accweb#53]
What is this supposed to show anyway? I have never seen any text in there since I started using this interface long ago.

I'm looking for an easy way to see driver connects with info, like Steam64 ID and such, instead of searching through the text log file in the folder.

**Comment by Kugelschieber** [comment]
It helps you to find issues and solve them. If you don't see the log output it's broken.

**Comment by Menteroth** [comment]
Well, if it's only issues I guess there hasn't been any. Because I never had any problems when a server has been online.

Would the other thing I mentioned be doable as a feature perhaps?

**Comment by Kugelschieber** [comment]
Yeah it's possible but I don't have time to do it right now.

**Comment by Menteroth** [comment]
That's fine. Just checking to see. Not trying to rush you or anything. I greatly appreciate your work.

**Comment by pedrofaria** [comment]
released
