### ISSUE TITLE
[Error] Export Config

### ISSUE THREAD

**Issue by Menteroth** [assetto-corsa-web/accweb#54]
![image](https://user-images.githubusercontent.com/24851042/79065975-8ffe8100-7cb4-11ea-8c63-6742c9a5e878.png)

**Comment by Kugelschieber** [comment]
When does this happen exactly?

**Comment by Menteroth** [comment]
When I click 'export config'.

**Comment by dam09fr** [comment]
I've noticed that if I use some special characters like '#' in the servername the export function does not work du tu lack of escaping in the URL.

**Comment by Menteroth** [comment]
All my server names have `|` in them.

**Comment by dam09fr** [comment]
Not sure how to do this but I think "${this.server.settings.serverName}" needs to be encoded by functions like encodeURIComponent() :
![image](https://user-images.githubusercontent.com/657562/79068619-97c82080-7cc8-11ea-9e34-2ecb1e3fe5c2.png)

**Comment by Kugelschieber** [comment]
Yes the server name can be anything which doesn't work for URLs. The backend doesn't care about the URL, only the id that is passed as a parameter is used to export the server (see https://github.com/assetto-corsa-web/accweb/blob/master/api/server.go#L199). So we can change that to something else...

**Comment by Kugelschieber** [comment]
Fixed: https://github.com/assetto-corsa-web/accweb/blob/master/public/src/components/server.vue#L51

**Comment by Menteroth** [comment]
Is this something I can fix locally or just wait for next update?

**Comment by Kugelschieber** [comment]
Wait for the next release.
