### ISSUE TITLE
assistRules.json Import

### ISSUE THREAD

**Issue by MirkoPlachta** [assetto-corsa-web/accweb#56]
Hi,

When I wan't to import Server settings, using assistRulse created like it's meant to be:

`{
  "stabilityControlLevelMax": 100,
  "disableAutosteer": 1,
  "disableAutoLights": 0,
  "disableAutoWiper": 0,
  "disableAutoEngineStart": 0,
  "disableAutoPitLimiter": 0,
  "disableAutoGear": 1,
  "disableAutoClutch": 0,
  "disableIdealLine": 1
}`

Then I get an "Error importing configuration files, please check your input."

It's because the import only accepts files with "true" "false" and not "0" "1" like this one:

`{"configVersion":1,"stabilityControlLevelMax":100,"disableAutosteer":true,"disableAutoLights":false,"disableAutoWiper":false,"disableAutoEngineStart":false,"disableAutoPitLimiter":false,"disableAutoGear":true,"disableAutoClutch":false,"disableIdealLine":true}`

Is it possible to fix this and also accept import of standard fomated files?

**Comment by Kugelschieber** [comment]
It's possible to change this to either use strings for everything (which it does right now) or the proper types. I don't remember why I chose to use strings for everything. What does the desktop server config tool spits out?

**Comment by MirkoPlachta** [comment]
Thanks for the quick answer.
Would be great if you switch to proper types.
Which tool do you mean?

**Comment by Kugelschieber** [comment]
I think AC had a desktop tool to configure servers... Wrong game :)
I'm not sure ACC will accept the json files if the attributes are not strings. Can you check that?

**Comment by MirkoPlachta** [comment]
Hi,
Of course it works, as it is the official way to create an assistRules.json
You can see it on page 10.
[ServerAdminHandbook_v7c.pdf](https://github.com/assetto-corsa-web/accweb/files/4537767/ServerAdminHandbook_v7c.pdf)

**Comment by Kugelschieber** [comment]
Thanks!

**Comment by Kugelschieber** [comment]
Fixed.
