### ISSUE TITLE
Assists Rules Menu / Cannot manually validate choices among various criteria

### ISSUE THREAD

**Issue by Emilio077** [assetto-corsa-web/accweb#57]
Hello,

First, very well done job for the awesome and very reliable program you have created.

I'm using a lot Accweb server program to set lobbies in ACC, and since version 1.8.0 and now 1.9.1, assists rules sub menu is available to allow or ban any of the various criteria. The matter is, whatever the selections I manually choose in this menu when I'm situated in the Localhost, as soon as I save the settings, the program brings back to default settings the assists rules menu, so I cannot "control" it. This is disturbing cause it every time allows stability control to 100% and all the assists...

Also, in 1.8.0 version, amazingly, here by default in the assist rules menu, stability control is at zero, ideal line disable. Nevertheless, If for example I activate idela line in the game whole settings, I can you it on track... Furthermore, in the same way (like V. 1.9.1), i cannot manually change assist criteria. 

I thank you anyone in advance for any assistance you may offer me.
Regards.

**Comment by Kugelschieber** [comment]
Yes this is a known bug.

**Comment by Emilio077** [comment]
Hi Marvin, thanks for the reply

Seems like the in-game assists criteria can be used, whatever those allowed or banned in the server.... Oh dear...

**Comment by Emilio077** [comment]
hmm..., no, if I use the server, car is looking the same without or with 100% stability control coming from the in-game assists menu

**Comment by Kugelschieber** [comment]
Fixed.
