### ISSUE TITLE
exit status 3221225781

### ISSUE THREAD

**Issue by xaviortiz** [assetto-corsa-web/accweb#58]
Hello

For some days server can't start.  
Logs are empty  :(

I tryed to delete instance, create new one.

thanks in advance for your time.
Xavi

**Comment by Kugelschieber** [comment]
Hm there must be something...

**Comment by Kugelschieber** [comment]
I'm closing this as I cannot help you without more information. Try version 1.9.2 I just released.

**Comment by xaviortiz** [comment]
Hi Marvin,

Please let me know what info do you need in order to investigate it.

I receive your mail but you don't ask me or comment about.

If you need some log, files, etc.  Please let me know.

Thanks in advance

**Comment by Kugelschieber** [comment]
Just go ahead and install version 1.9.2 and try again. I need the accweb logs and possible browser logs.
