### ISSUE TITLE
Password encryption

### ISSUE THREAD

**Issue by gillesdubois** [assetto-corsa-web/accweb#59]
Hi,

I'm not really a GO / Vue expert thus i don't know if this is complex to implement or not but it would be nice to have encrypted password in the config.yml. 

For obvious security reason its always nice to have encrypted pass even if i guess that most people run this app behind a proxy or with a restricted access.

Regards,
Gilles Dubois.

**Comment by Kugelschieber** [comment]
We can probably add base64 encoding to all passwords, but if someone gets access to your server you're screwed anyway. The config.yml is supposed to exist just on the server.

**Comment by Kugelschieber** [comment]
Or even better, hash the passwords within the `config.yml` and then hash them on login...

**Comment by Kugelschieber** [comment]
I will close this as it doesn't provide much value and makes the configuration more complicated for "non technical" users. As the config residents on the server it should be safe enough.
