### ISSUE TITLE
Internal serveur error

### ISSUE THREAD

**Issue by ggbsnowbird** [assetto-corsa-web/accweb#60]
Hi. thanks for the great work. On Linux, issue with webserver. Displays a 500 internal error whatever the config.

**Comment by Kugelschieber** [comment]
Can you show your config (remove passwords and other sensible information)? Is it behind a firewall, proxy or something?

**Comment by ggbsnowbird** [comment]
Console when starting => (passwords have been changed afterwards)
accweb is in the server folder itself. server is already configured but not started. (working to get the results right now).
=================
ubuntu@vsr-acc-1:~/VSR/serverACCMONZA$ wine ./accweb.exe
time="2020-04-26T19:25:17Z" level=info msg="Loading configuration file"
time="2020-04-26T19:25:17Z" level=info msg="\ndev: false\nloglevel: debug\nconfig_path: config/\nwebserver:\n    host: 51.178.56.193:8080\n    write_timeout: 5\n    read_timeout: 5\n    tls: false\n    cert: path to ssl certificate\n    private_key: path to ssl private key\ncors:\n    origins: '*'\n    loglevel: info\nauth:\n    public_key_path: secrets/token.public\n    private_key_path: secrets/token.private\n    admin_password: VSRPP\n    moderator_password: VSRPPM\n    read_only_password: VSRPPR\nacc:\n    server_path: /\n    server_exe: wine ./accServer.exe\n"
time="2020-04-26T19:25:17Z" level=info msg="Configure logging..."
time="2020-04-26T19:25:17Z" level=info msg="Loading build.js..."
time="2020-04-26T19:25:17Z" level=info msg="Loading server list..."
time="2020-04-26T19:25:17Z" level=info msg="Server list loaded successfully" servers=0
time="2020-04-26T19:25:17Z" level=info msg="Configuring CORS..."
time="2020-04-26T19:25:17Z" level=info msg="Starting server..."

===============
Config.yml =>
# accweb server and application configuration.
# https://github.com/assetto-corsa-web/accweb

webserver:
  # Sets the host and port.
  # Port 80 is the default port for web servers and might be blocked on your maschine.
  # If that is the case you can use anything else like 8080 for example.
  host: 51.178.56.193:8080

  # Set tls to true and provide paths to the key files in order to enable SSL.
  # This is highly recommended as otherwise your passwords and all other traffic won't be encrypted!
  # accweb will probably support automatic Letsencrypt certificates in the future.
  tls: false
  cert: path to ssl certificate
  private_key: path to ssl private key

  # http write/read timeouts
  # technical stuff you shouldn't mess around with
  write_timeout: 5
  read_timeout: 5

auth:
  # Set the admin, moderator and read only user password.
  # accweb won't start without an admin password.
  admin_password: VSRPP
  moderator_password: VSRPPM
  read_only_password: VSRPPR

  # Path to public and private token key files.
  # These must be provided as they are required to generate save tokens for authentication.
  # accweb won't start without them. They will be automatically generated if accweb finds the gen_rsa_keys script
  # next to the accweb executable. So you will most likely be able to start the server without touching this.
  public_key_path: secrets/token.public
  private_key_path: secrets/token.private

acc:
  # Path to ACC server installation directory.
  # Use forward slashes (even if you're on Windows!). The example path is for Linux.
  server_path: "/"

  # Name of the server executable within the server installation directory.
  # You don't need to change this (except the ACC devs change its name for some reason).
  server_exe: wine ./accServer.exe

**Comment by Kugelschieber** [comment]
Try changing host to just `0.0.0.0:8080`. `51.178.56.193:8080` will listen just to that specific ID.

**Comment by ggbsnowbird** [comment]
Same result. I also tried on W3M from the terminal directly.
No IPTables.
AccWeb runs its own webserver correct ?

**Comment by Kugelschieber** [comment]
Yes. Can you access it on your machine (through curl for example)?

**Comment by ggbsnowbird** [comment]
Got it below
```
ubuntu@vsr-acc-1:~$ curl -o accweb500.html http://0.0.0.0:8080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    26  100    26    0     0   2600      0 --:--:-- --:--:-- --:--:--  3250
ubuntu@vsr-acc-1:~$ cat accweb500.html 
500 Internal Server Error
```

**Comment by ggbsnowbird** [comment]
Can it be some read / write / execute issue ?

**Comment by Kugelschieber** [comment]
Probably yes, the logs should actually tell you in this case what's wrong.

**Comment by ggbsnowbird** [comment]
Sorry, dummy question, where the logs for accweb ?

**Comment by Kugelschieber** [comment]
They're just spit out to standard output. So in your terminal.

**Comment by ggbsnowbird** [comment]
Yes ok, that's what I had in mind.
I just have this, and no more after "starting server" 
```
ubuntu@vsr-acc-1:~/VSR/serverACCMONZA$ wine ./accweb.exe
time="2020-04-26T19:25:17Z" level=info msg="Loading configuration file"
time="2020-04-26T19:25:17Z" level=info msg="\ndev: false\nloglevel: debug\nconfig_path: config/\nwebserver:\n    host: 51.178.56.193:8080\n    write_timeout: 5\n    read_timeout: 5\n    tls: false\n    cert: path to ssl certificate\n    private_key: path to ssl private key\ncors:\n    origins: '*'\n    loglevel: info\nauth:\n    public_key_path: secrets/token.public\n    private_key_path: secrets/token.private\n    admin_password: VSRPP\n    moderator_password: VSRPPM\n    read_only_password: VSRPPR\nacc:\n    server_path: /\n    server_exe: wine ./accServer.exe\n"
time="2020-04-26T19:25:17Z" level=info msg="Configure logging..."
time="2020-04-26T19:25:17Z" level=info msg="Loading build.js..."
time="2020-04-26T19:25:17Z" level=info msg="Loading server list..."
time="2020-04-26T19:25:17Z" level=info msg="Server list loaded successfully" servers=0
time="2020-04-26T19:25:17Z" level=info msg="Configuring CORS..."
time="2020-04-26T19:25:17Z" level=info msg="Starting server..."
```

**Comment by Kugelschieber** [comment]
I just saw you executing the windows version of accweb on ubuntu? Is there a reason not to use the linux executable?

**Comment by ggbsnowbird** [comment]
not a good reason... it is working. Sorry for wasting your time... and thanks again for this great contribution. I will support it.

**Comment by Kugelschieber** [comment]
You're welcome :)
