### ISSUE TITLE
Default Grid Position wrong position?

### ISSUE THREAD

**Issue by gjelsoe** [assetto-corsa-web/accweb#63]
According to Server handbook 7c, the defaultGridPosition should not be within the Driver tag.

{
"drivers": [
{
"firstName": "First",
"lastName": "Driver",
"shortName": "NO1",
"driverCategory": 2,
"playerID": "S765611xxxxxxxxxx3"
},
{
"firstName": "Another",
"lastName": "Person",
"shortName": "NO2",
"driverCategory": 1,
"playerID": "S765611xxxxxxxxxx4"
}
],
"raceNumber": 114,
"forcedCarModel": -1,
"overrideDriverInfo": 0,
"defaultGridPosition": -1,
"ballastKg": 0,
"restrictor": 0,
"customCar": "exampleCar.json",
"overrideCarModelForCustomCar": 1,
"isServerAdmin": 0
}

**Comment by Kugelschieber** [comment]
Is it in the wrong place or just obsolete?

**Comment by gjelsoe** [comment]
It seems it's the wrong place.
