### ISSUE TITLE
Assist rules are not being saved

### ISSUE THREAD

**Issue by assetto** [assetto-corsa-web/accweb#64]
All the below settings can not be changed. When I change it and save the config on return it is still default. 

Stability Control Level Max: 0 to 100 max 
100
Disable Auto-Steer
Disable Auto-Lights
Disable Auto-Wiper
Disable Auto-Engine Start
Disable Auto Pit Limiter
Disable Auto-Gear
Disable Auto-Clutch
Disable Ideal Line

**Comment by Kugelschieber** [comment]
Which version? I fixed this in 1.9.2

**Comment by assetto** [comment]
accweb_1.9.1.... so I missed a version?

**Comment by Kugelschieber** [comment]
Yes
