### ISSUE TITLE
EventRules

### ISSUE THREAD

**Issue by rivotril0** [assetto-corsa-web/accweb#67]
Apparently the file is written correctly, but it fails to load leaving the default options (all disabled)

**Comment by Kugelschieber** [comment]
Which version of accweb?

**Comment by rivotril0** [comment]
latest

**Comment by Kugelschieber** [comment]
![eventrules](https://user-images.githubusercontent.com/6115423/81003201-c14d1580-8e4a-11ea-9c5d-7017e2a6deba.gif)
