### ISSUE TITLE
accServer stdout -> emit (socket io)

### ISSUE THREAD

**Issue by rivotril0** [assetto-corsa-web/accweb#68]
Live stints, crash, penalityes, results, etc

**Comment by Kugelschieber** [comment]
You mean output those to the logs?

**Comment by rivotril0** [comment]
I am not a go developer, so I am a bit lost in the code. What I mean is that every time stdout has an update emit it by socket, the client implementation is out of scope

**Comment by Kugelschieber** [comment]
Ah okay. Right now you need to refresh manually. The simplest solution would be to add polling every few seconds, which should be good enough.

**Comment by rivotril0** [comment]
Think in the way of integration with other platforms, not as an improvement of the actual implementation, most league have their own website for inscription, hotlaps, bla bla

**Comment by pedrofaria** [comment]
live view release without web socket implementation. maybe in the future
