### ISSUE TITLE
Docker image missing configuration

### ISSUE THREAD

**Issue by Bensge** [assetto-corsa-web/accweb#71]
Hello,

I tried deploying the docker image, but it seems like the image is missing necessary configuration. Firstly, the example command in the readme
```
docker run -it accweb -p 2600:2600 2601:2601
```
is not correct. It should be
```
docker run -p 2600:2600 -p 2601:2601 -p 8080:8080 -it accweb
```
Secondly, the web server would reject network requests from the host machine or any other machine besides from the docker container until I changed the host environment variable to
```
ACCWEB_HOST=0.0.0.0:8080
```

Next, I cannot get the docker image to successfully run the server exe file with wine. accweb tries to execute `wine`, but that executable doesn't exist in the container at all. Only `wine64` exists. However, wine64 also cannot run the server successfully. This is the output from wine64:

<details>
<summary>Long wine64 error messages</summary>
wine: created the configuration directory '/root/.wine'
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0012:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0012:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
0012:err:ole:get_local_server_stream Failed: 800736b7
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0016:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0016:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0016:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0010:err:module:import_dll Loading library urlmon.dll (which is needed by L"C:\\windows\\system32\\mshtml.dll") failed (error c000007b).
0010:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
wine: configuration in '/root/.wine' has been updated.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0009:fixme:msvcp:_Concurrent_queue_base_v4_ctor (0x21f118 32) stub
0009:fixme:msvcp:_Mtx_init_in_situ unknown flags ignored: 1
0009:fixme:msvcp:_Concurrent_queue_base_v4_ctor (0x21f528 8) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21ef10) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21eac0) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21ea80) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21eb70) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21ead0) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21ead0) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21e7e0) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21ead0) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21ea90) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21e530) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
002b:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f118 0x65fd88) stub
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21e530) stub
0009:fixme:msvcp:_Mtx_init_in_situ unknown flags ignored: 1
0009:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x21ef10) stub
002e:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x98f730) stub
002e:fixme:msvcp:_Mtx_init_in_situ unknown flags ignored: 1
002e:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f528 0x98f8f0) stub
002e:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x98edc0) stub
002e:fixme:msvcp:_Concurrent_queue_base_v4__Internal_push (0x21f118 0x98edc0) stub
0030:fixme:msvcp:_Concurrent_queue_base_v4_ctor (0x35a790 8) stub
002f:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f528 0xa9f8f0) stub
TCP connect returns: 0
002e:fixme:msvcp:_Concurrent_queue_base_v4__Internal_pop_if_present (0x21f528 0x98f8f0) stub
</details>

I didn't get further than this. I guess some TrueType fonts and maybe some wine libs are missing.
Also, maybe wine needs to be told to run in headless mode?

It would be great to get the docker image up and running with full functionality. Cheers!

**Comment by Kugelschieber** [comment]
@gillesdubois

**Comment by gillesdubois** [comment]
Hi,

My bad the dockerfile provided is not complete i didn't push all the modifications.
Will do a PR correcting that tomorrow when i will have access to my computer.

Regards,
Gilles Dubois.

**Comment by Kugelschieber** [comment]
@Bensge can you try again?

**Comment by v4rakh** [comment]
Hi, regarding docker, I tried out the `docker-compose` variant and I always get 

```
sudo docker-compose up                                                                                                             [0]
Creating volume "accweb_accweb" with default driver
Creating volume "accweb_acccerts" with default driver
Creating volume "accweb_accserver" with default driver
Creating accweb ... error

ERROR: for accweb  Cannot start service app: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/accweb/docker-entrypoint.sh\": permission denied": unknown

ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/accweb/docker-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```

I modified the file to match my needs and to use the uploaded docker hub image. I also added a host bind so that I don't have to move the `accServer.exe` into the volume over and over again. Do you see any obvious mistake I made here?

```
version: '3'

services:
  app:
    image: kugel/accweb:latest
    container_name: accweb
    restart: always
    ports:
      - 9595:8080
      - 9321:9321/udp
      - 9322:9322/tcp
    volumes:
      - "accweb:/accweb"
      - "acccerts:/sslcerts"
      - "./accserver:/accserver"
    environment:
      ACCWEB_HOST: 0.0.0.0:8080
      ACCWEB_ENABLE_TLS: "false"
      ACCWEB_CERT_FILE: /sslcerts/certificate.crt
      ACCWEB_PRIV_FILE: /sslcerts/private.key
      ACCWEB_ADMIN_PASSWORD: pass1
      ACCWEB_MOD_PASSWORD: pass2
      ACCWEB_RO_PASSWORD: pass3
      ACCWEB_LOGLEVEL: info
      ACCWEB_CORS: "*"
    networks:
      - accnetwork

networks:
  accnetwork:

volumes:
  accweb:
  acccerts:
  #accserver:
```

**Comment by gillesdubois** [comment]
Hi @Bensge ,

Yes docker entrypoint have executable permissions set.
I'm looking at your issue today.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
I found the origin of the problem, it seem my git doesn't care of permissions and it didn't push it properly.

I will create a PR to fix in a few minutes.

Note : you will have to remove the volumes to get the permissions right 

Here is the list of tests that have been performed on the following hosts (and with server up and running) by running i mean played assetto on the server without any issues : 
- Ubuntu 18.04 LTS => Docker version 19.03.8, build afacb8b7f0 => OK
- Ubuntu 20.04 LTS => Docker version 19.03.8, build afacb8b7f0 => OK
- Centos 7 => Docker version 19.03.8, build afacb8b => OK
- Ubuntu 18.04 LTS (Desktop) => Docker version 19.03.5, build 633a0ea => OK
- Windows 10 docker desktop => Docker version 19.03.5, build 633a0ea => OK

**Comment by v4rakh** [comment]
Thanks, it's working.
