### ISSUE TITLE
Docker image hangs on 'Starting server...'

### ISSUE THREAD

**Issue by dark-vex** [assetto-corsa-web/accweb#75]
I have tried to build on Debian 10 and on Centos 8 host the docker image (I tried also the one published on docker hub) but when I run:

`docker run -it kugel/accweb -p 8080:8080 -p 2600:2600 -p 2601:2601
`
or 

`docker run -it accweb -p 8080:8080 -p 2600:2600 -p 2601:2601
`
the container always hangs on "Starting server", I waited also 30 minutes but keeps hanging on that, below the docker run output:

```
it looks like wine32-development is missing, you should install it.
multiarch needs to be enabled first.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32-development"
wine: created the configuration directory '/root/.wine'
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0014:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
0014:err:ole:get_local_server_stream Failed: 800736b7
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not load wine-gecko. HTML rendering will be disabled.
it looks like wine32-development is missing, you should install it.
multiarch needs to be enabled first.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32-development"
0027:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0027:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.
0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0009:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
INFO[0000] Loading configuration file
INFO[0000]
dev: false
loglevel: info
config_path: config/
webserver:
    host: localhost:8080
    write_timeout: 5
    read_timeout: 5
    tls: false
    cert: /sslcerts/certificate.crt
    private_key: /sslcerts/private.key
cors:
    origins: '*'
    loglevel: info
auth:
    public_key_path: secrets/token.public
    private_key_path: secrets/token.private
    admin_password: weakadminpassword
    moderator_password: weakmodpassword
    read_only_password: weakropassword
acc:
    server_path: /accserver
    server_exe: accServer.exe
INFO[0000] Configure logging...
INFO[0000] Loading build.js...
INFO[0000] Loading server list...
INFO[0000] Server list loaded successfully               servers=0
INFO[0000] Configuring CORS...
INFO[0000] Starting server...
```

**Comment by Kugelschieber** [comment]
@gillesdubois didn't we fix that lately?

**Comment by gillesdubois** [comment]
Hi,

Yes this problem has been fixed. I will check that this evening but imo its working properly.

Regards,
Gilles Dubois.

**Comment by Kugelschieber** [comment]
accweb seems to have started properly, but why does it try to create a window? `000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.` That's not possible on a server I guess :)

**Comment by Dark-Vex** [comment]
@Kugelschieber So adding/installing xvfb package in the docker container should resolve the issue for Linux systems without graphical interface

**Comment by Kugelschieber** [comment]
Well it shouldn't try to create a window in the first place. The ACC server is completely terminal based. I'll leave this to Gilles :P

**Comment by thecynicalcanuck** [comment]
Hi, I'm having the exact same issues as described by Dark Vex, I've attempted to run the server on Ubuntu Server 20.04

**Comment by HectorBart** [comment]
Same problem here, has anyone found a solution yet? 

`it looks like wine32-development is missing, you should install it.

multiarch needs to be enabled first. as root, please

execute "dpkg --add-architecture i386 && apt-get update &&

apt-get install wine32-development"

=0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.

0009:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.

>INFO[0000] Loading configuration file

INFO[0000]

dev: false

loglevel: info

config_path: config/

webserver:

host: localhost:8080

write_timeout: 5

read_timeout: 5

tls: false

cert: /sslcerts/certificate.crt

private_key: /sslcerts/private.key

cors:

origins: '*'

loglevel: info

auth:

public_key_path: secrets/token.public

private_key_path: secrets/token.private

admin_password: weakadminpassword

moderator_password: weakmodpassword

read_only_password: weakropassword

acc:

server_path: /accserver

server_exe: accServer.exe

INFO[0000] Configure logging...

INFO[0000] Loading build.js...

INFO[0000] Loading server list...

INFO[0000] Server list loaded successfully servers=0

INFO[0000] Configuring CORS...

INFO[0000] Starting server...`

**Comment by Dark-Vex** [comment]
@HectorBart no resolution so far, is still not working for me

**Comment by Kugelschieber** [comment]
I'll close this, Docker won't be supported until v2.
