### ISSUE TITLE
Obfuscate passwords in logs

### ISSUE THREAD

**Issue by fattylewis** [assetto-corsa-web/accweb#78]
Hey,

Would it be possible to obfuscate the passwords in the running log.
I'm running accweb through a sytemd service file and dont really like passwords ending up in syslog. 

Nothing major, more of a suggestion.

Cheers!

Jon

**Comment by Kugelschieber** [comment]
You're talking about the server logs, right? Not accweb itself? That's not possible I'm afraid.

**Comment by pedrofaria** [comment]
tha config.yml file was printed in the bootstrap of accweb. not anymore :)
