### ISSUE TITLE
Not Sure whats wrong as new to ACC Web

### ISSUE THREAD

**Issue by AKM-Andy** [assetto-corsa-web/accweb#79]
I am getting this error in terminal window......

time="2020-07-01T22:31:30+01:00" level=fatal msg="Error generating key files through OpenSSL. Make sure the script gen_rsa_keys is in place" err="exit status 1"

The file gen_rsa_keys.cmd is in folder with accweb.exe

Any help would be appreciated

Andy

**Comment by Kugelschieber** [comment]
Run it manually once.

**Comment by AKM-Andy** [comment]
Thank You for a fast response

Download necessary components
Exception calling "DownloadFile" with "2" argument(s): "The underlying
connection was closed: An unexpected error occurred on a send."
At line:1 char:47
+ ... .WebClient; $client.DownloadFile('https://bintray.com/vszakats/generi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Is what I get when I run gen_rsa_keys.cmd

**Comment by Kugelschieber** [comment]
Can you install OpenSSL manually and uncommend line 3 to 7 within the script? It seems like the link is broken.

**Comment by AKM-Andy** [comment]
Hi, thats beyond me could you not send me another file plz & thank you so much for a great piece of software from what I have read

**Comment by Kugelschieber** [comment]
I'll update it :)

**Comment by AKM-Andy** [comment]
lol sorry I'm ok at most stuff but a master of none lol - thanks

**Comment by AKM-Andy** [comment]
Hi any idea of a time frame plz so I can sort my blue jobs around it lol

**Comment by Kugelschieber** [comment]
Tomorrow I hope.

**Comment by AKM-Andy** [comment]
Hi Kugelschieber I have installed OpenSSH lol but still no luck

**Comment by Kugelschieber** [comment]
Ok I looked at the script and it seems to be able to download OpenSSL just fine. Try to create a directory "secrets" next to the accweb.exe and put two files into it. One called "token.private", the other "token.public". You can generate the contents here: https://travistidwell.com/jsencrypt/demo/ The private key goes to the token.private file and the other to token.public.

**Comment by AKM-Andy** [comment]
Thanks for response - what are these keys for as not sure what to type into box at the link you sent me?

**Comment by Kugelschieber** [comment]
Perfekt!

The keys are used to encrypt the tokens used for authentication. When you log in you get one that can be decrypted on the server to identify you. I just noticed the key size is set to 1024 bit by default. I would recommend increasing that to 4096.

**Comment by AKM-Andy** [comment]
lol I already noticed that and changed it lol - I'm now struggling to connect to it but gimme a bit will sort it

**Comment by Kugelschieber** [comment]
Have you configured the passwords correctly?

**Comment by AKM-Andy** [comment]
Its all working as was Port Number so changed it to another & it lept into action & WOW its amazing thank you so much for your help - your more than welcome anytime on our servers or watch us at https://www.twitch.tv/akm_racing_uk

Andy

**Comment by AKM-Andy** [comment]
Sorry to ask again but whats the difference between admin & moderator user passwords as can only see the read only changes?

**Comment by Kugelschieber** [comment]
The moderator can start/stop server but cannot change settings.

**Comment by AKM-Andy** [comment]
OK thank you and can ALL Servers results go into 1 folder as I run ACC Results Companion which will only connect to 1 folder?

**Comment by Kugelschieber** [comment]
Not at the moment.

**Comment by AKM-Andy** [comment]
OK and last question can I start accweb.exe with a .BAT file and is so can u paste me code required in it please?

**Comment by Kugelschieber** [comment]
I'm not a Windows user, so I don't know how that works. But you can surely start accweb from a bat file.

**Comment by AKM-Andy** [comment]
OK no worries is path to central entrylist.json forward slashes /// like C:/Folder/Folder/   ???

**Comment by Kugelschieber** [comment]
You should use backward slashes on Windows. In quotes, you might need to escape them with another slash in front of them. @cestcomi might know more about this. I think I runs a Windows server?

**Comment by AKM-Andy** [comment]
Hi Kugelschieber I have it fully working thanks for your help - It would be really nice if I could move servers up/down the list so maybe a future update?

Thanks again its brilliant
