### ISSUE TITLE
[ENHANCEMENT] Clients Counter

### ISSUE THREAD

**Issue by AKM-Andy** [assetto-corsa-web/accweb#80]
Hi I would like to see 10/12 being the corresponding number of clients on server out of maximum allowed - I run an online racing Team & some of my Drivers are Admins - I have setup a FULL list of servers for each circuit including the new British ones & a few extras so have a list of 22 Servers - The VPS I am running my servers on has limitations so the Admins know we can only run 10 at any one time so if they want to start a particular circuit thats not running & theris 10 already running they need to see whic ones are NOT populated before switching any off - it wud fit nicley to left of START/STOP Button.

Thanks for an excellent piece of software

Andy
AKM Racing UK

**Comment by Kugelschieber** [comment]
I guess this would require to analyze the game server logs in real-time. I need to look into this when I got some time to do it, which won't happen very soon.

**Comment by AKM-Andy** [comment]
Hi Marvin the server sends that info to Server List via port number selected so maybe monitoring the port for the specific info might be better?????

**Comment by pedrofaria** [comment]
released
