### ISSUE TITLE
tyreSetCount setting for eventRules.json

### ISSUE THREAD

**Issue by athmoss** [assetto-corsa-web/accweb#90]
Hello,
there is an undocumented setting, tyreSetCount, in the eventRules.json which limits the tyre sets usable per race weekend. See [acc-wiki](https://www.acc-wiki.info/wiki/Server_Configuration#eventRules.json)
Could this be implemented? Thanks!

**Comment by Kugelschieber** [comment]
Added in 1.11.0.
