### ISSUE TITLE
Encoding of import files

### ISSUE THREAD

**Issue by MirkoPlachta** [assetto-corsa-web/accweb#91]
Hello, 

Import is only working, if json files are encoded in UTF-8 
But as it can be read in ServerAdminHandbook it schould be UTF16-LE:

>  III.2 Configuration files The server is exclusively configured via JSON files in UTF16-LE format. Using UTF8 file encodings may seem to work but will lead to wrong readings. In general, it is a good idea to get used to the JSON syntax, and/or test your configurations with an online syntax check.

**Comment by kiview** [comment]
In addition, UTF-8 encoded files might indeed lead to errors and prevent startup of the server, as it is the case with #108.

**Comment by smaxx1337** [comment]
hey, is there any update on this?

**Comment by Kugelschieber** [comment]
No sorry, there is still no easy way to fix this. I tried converting utf-8 to utf-16 by myself, but that didn't really work.

**Comment by smaxx1337** [comment]
https://gist.github.com/sail1972/c7f2da14d0f284f7d76a5afce7daacfc maybe this can help? Not sure tho

**Comment by Kugelschieber** [comment]
That might work.
