### ISSUE TITLE
Check server name for illegal characters (fs)

### ISSUE THREAD

**Issue by Kugelschieber** [assetto-corsa-web/accweb#92]

**Comment by robca402** [comment]
Out of interest, is there a documented list of illegal characters? Is a - an illegal character? Trying to troubleshoot why my servers are crashing when making changes to one lobby

**Comment by Kugelschieber** [comment]
Everything character that is not allowed within a filename/path is illegal, as accweb will create a directory by the name you've set for the server. So slashes and backslashes are usually the problem. I would recommend using "normal" characters (a-Z, 0-9), underscores, dots, and hyphens. So instead of using "Servername 24/7" use "Servername 24-7" instead.

**Comment by Kugelschieber** [comment]
I'll fix this in v2. Instead of using the name for the directory, I'll use something else.

**Comment by robca402** [comment]
Thanks so much, would appreciate that. For now glad I know why it was crashing!

**Comment by pedrofaria** [comment]
Fixed with #150 

Will be released soon
