### ISSUE TITLE
Possibility to start servers on hight priority

### ISSUE THREAD

**Issue by madrippeur** [assetto-corsa-web/accweb#93]
Hello,
Not really an issue, but a good request !
When a new player is connecting to one server, we have some lags.
I tested to put server in hight priority mode in windows, and it look good. But if i stop and start the server, the priority is normal.

Could you make the possibility to start automaticaly servers with Hight priority on windows please ?

START "" /HIGH server.exe :) 
(sorry for my bad english, i'm french !)

**Comment by pedrofaria** [comment]
implemented and will be released on version v1.19.0
