### ISSUE TITLE
Cannot add / into server name

### ISSUE THREAD

**Issue by robca402** [assetto-corsa-web/accweb#94]
Any time I add a / into a server name it locks up my lobbies. I am wanting to add discord URL which I see some other lobbies have successfully done. Find attached image of someone else's server.
![acc server name](https://user-images.githubusercontent.com/48463801/91002536-0c21b180-e623-11ea-8698-c02f721d78b1.jpg)

Steps to reproduce:
Add a / into a server name anywhere. When saved and started it will not be able to be stopped, and console output will either be blank if it had not been run before, or display the log output from it's last successful run. It often crashes other server instances that were running.

I think it crashes wine on Ubuntu.

It is a working install, with everything operating as it should until I rename a server with a / in the name.

This is on Ubuntu 20.04 with accweb 1.10.1 and latest accServer.exe and wine-development as of 24/8/20.

I'm sure I will need to provide more information so don't hesitate to ask, I'm new to how github works.

**Comment by Kugelschieber** [comment]
See https://github.com/assetto-corsa-web/accweb/issues/92

It's not possible to use characters that are illegal in filenames at the moment. I'll fix that in v2.
