### ISSUE TITLE
Fresh Install not launching fatal (msg="build.js not found)

### ISSUE THREAD

**Issue by Shockkota** [assetto-corsa-web/accweb#95]
I see the file included in older versions but not the current. Unsure if this is a bug on my end or a reference that wasn't updated. The full error is below. 

`time="2020-08-25T15:07:46-05:00" level=info msg="Configure logging..."
time="2020-08-25T15:07:46-05:00" level=info msg="Loading build.js..."
time="2020-08-25T15:07:46-05:00" level=fatal msg="build.js not found" err="open public/dist/build.js: The system cannot find the path specified."`

**Comment by Kugelschieber** [comment]
It is in the bundle. Have you extracted the zip file properly?

**Comment by Shockkota** [comment]
You are correct. Pulled the wrong thing, Sorry for the bother. Thanks for all of your work on this.
