### ISSUE TITLE
IsFixedConditionQualification 

### ISSUE THREAD

**Issue by kj5dpl** [assetto-corsa-web/accweb#97]
https://github.com/assetto-corsa-web/accweb/blob/36f07849e7c71f0fba9f61d359cd2dff57d2e954/server/server.go#L65

SimracerWeatherConditions and ZIsFixedConditionQualification  should be int instead of bool

if bool used in config file it has no effect on ACC server
if I change to 1 manual in config file accweb crashes at start

![image](https://user-images.githubusercontent.com/43707985/92951841-55656400-f45f-11ea-809d-6f5e347db034.png)

**Comment by Kugelschieber** [comment]
Does this apply to all boolean parameters (like IsRefuellingAllowedInRace for example)? I haven't looked into the documentation for a while.

**Comment by kj5dpl** [comment]
We discovered errors only those two. What about a trade: I will check all typer in documentation and you will fix this one ASAP :-)

**Comment by kj5dpl** [comment]
[ServerAdminHandbook_v8.pdf](https://github.com/assetto-corsa-web/accweb/files/5210575/ServerAdminHandbook_v8.pdf)

**Comment by Kugelschieber** [comment]
Sounds good, but I'm not sure it's worth it as I plan to fix all this stuff in 2.0.
I'll look into it later or tomorrow, that should just take a few minutes.

**Comment by kj5dpl** [comment]
Ok - I have only found:

EventRulesJson  - tyreSetCount is missing
![image](https://user-images.githubusercontent.com/43707985/92953424-fe14c300-f461-11ea-8577-52419a545612.png)

**Comment by Kugelschieber** [comment]
Thanks, I'll add that too!

**Comment by Kugelschieber** [comment]
Here you go: https://github.com/assetto-corsa-web/accweb/releases/tag/1.11.0

**Comment by kj5dpl** [comment]
thx a lot
