### ISSUE TITLE
Error reading cpSecret

### ISSUE THREAD

**Issue by AKM-Andy** [assetto-corsa-web/accweb#99]
Hi not sure how to contact anyone but getting this error "Error reading cpSecret" after rebooting my VPS & trying to start ACC Web - it has run perfectly for months since we manually setup the tokens but now won't even start & got a race meeting tonight - plz help asap

Andy

**Comment by Kugelschieber** [comment]
That message is not part of accweb. Did you change anything? Did you upgrade or regenerate the secrets? What does the log output look like if you start accweb in the console?

**Comment by AKM-Andy** [comment]
Hi I have copied and pasted the log file below from Config/1594993075 folder - I haven't changed anything other than updated accserver.exe with new version of ACC v1.5.6 - I haven't touched the secrets - ACC Web will not even start when I double click accweb.exe

0: Server starting with version 255
0: Error reading cpSecret
0: Starting server AKM Racing UK | Hotlapping - 07/20
0: ==ERR: preRaceWaitingTimeSeconds (60) has been set to 80s, 1088949824 seconds are too low for public Multiplayer
0: 	EntryList entry: id 0, isAdmin 1, overrideDI 0
0: 	EntryList entry: id 1, isAdmin 1, overrideDI 0
0: 	EntryList entry: id 2, isAdmin 1, overrideDI 0
0: 	EntryList entry: id 3, isAdmin 0, overrideDI 0
0: 	EntryList entry: id 4, isAdmin 0, overrideDI 0
0: 	EntryList entry: id 5, isAdmin 0, overrideDI 0
0: Using entry list with 6 drivers
0: Joining during race is allowed
0: FileToStruct cfg/eventRules.json
0: SessionManager::randomizeGreenFlagTriggers: s:0.890000 e:0.950000 r:0.894195
0: Track monza_2019 was set and updated
0: Event changed
0: ==ERR: Ignoring special event rules for public Multiplayer
0: ==ERR: Ignoring special assist rules for public Multiplayer
0: SessionManager::randomizeGreenFlagTriggers: s:0.890000 e:0.950000 r:0.895633
0: Significant change detected, updating lobby (1|1)
0: Resetting weekend to friday night
0: Reset time to friday night: 0 -> 0
0: Reset time to first session: 0 -> 212400
0: SessionManager::randomizeGreenFlagTriggers: s:0.890000 e:0.950000 r:0.896367
0: Listening to TCP 9609 | UDP 9608

**Comment by Kugelschieber** [comment]
Hm I don't know, this is an issue with the game server itself. accweb is started from the directory you extracted the zip by running accweb.exe.

**Comment by AKM-Andy** [comment]
OK does ACC Web have a log file?

**Comment by Kugelschieber** [comment]
No, but you should see it if you start accweb.exe through the console. 
1. cd C:/path/to/accweb
2. accweb.exe -> Enter
This should start it and output something.

**Comment by Kugelschieber** [comment]
You can join Discord if you like: https://discord.gg/P3uG83

**Comment by AKM-Andy** [comment]
time="2020-09-12T12:41:57+01:00" level=fatal msg="Error loading server settings" error="invalid character 'ÿ' looking for beginning of value" name=1594992360
